import {useLanguage} from "../i18n";
import "../charts.css";
import {useEffect,useRef,useState} from 'react';
import {scaleLinear,line,area,bisector} from 'd3';
export interface SeriesPoint {x:number;y:number|null;group?:number}
export interface ChartSeries {name:string;color:string;values:SeriesPoint[];dashed?:boolean;area?:boolean}
export default function TimeSeries({title,unit,series,xLabel='Turn',minY=0,maxY}:{title:string;unit:string;series:ChartSeries[];xLabel?:string;minY?:number;maxY?:number}){
 const {t:tr,language}=useLanguage();
 const ref=useRef<HTMLDivElement>(null),[width,setWidth]=useState(700),[active,setActive]=useState<number|null>(null);
 useEffect(()=>{if(!ref.current)return;const observer=new ResizeObserver(([e])=>setWidth(Math.max(300,e.contentRect.width)));observer.observe(ref.current);return()=>observer.disconnect();},[]);
 const all=series.flatMap(s=>s.values),xs=Array.from(new Set(all.map(p=>p.x))).sort((a,b)=>a-b),lo=xs[0]??0,hi=xs.at(-1)??1,left=60,right=width-18,top=28,bottom=225;
 const x=scaleLinear().domain([lo,Math.max(lo+1,hi)]).range([left,right]),y=scaleLinear().domain([Math.min(minY,...all.map(p=>p.y??minY)),Math.max(maxY??minY+1,...all.map(p=>p.y??minY))]).nice(5).range([bottom,top]);
 const fmt=(value:number)=>new Intl.NumberFormat(language==='fr'?'fr-CA':'en-CA',{maximumFractionDigits:1}).format(value),index=active===null?null:Math.max(0,Math.min(xs.length-1,active)),selected=index===null?null:xs[index];
 const textAt=(v:number)=>`${tr(xLabel)} ${v}: ${series.map(s=>`${tr(s.name)} ${s.values.find(p=>p.x===v)?.y==null?tr('unavailable'):fmt(s.values.find(p=>p.x===v)!.y!)} ${tr(unit)}`).join('; ')}`;
 return <div ref={ref} className="d3-timeseries"><svg viewBox={`0 0 ${width} 270`} role="img" aria-label={`${tr(title)}. ${tr(unit)}. ${tr("Use arrow keys to inspect values.")}`} tabIndex={0} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();setActive(e.key==='Home'?0:e.key==='End'?xs.length-1:Math.max(0,Math.min(xs.length-1,(index??0)+(e.key==='ArrowRight'?1:-1))));}}} onMouseMove={e=>{const box=e.currentTarget.getBoundingClientRect(),v=x.invert((e.clientX-box.left)*width/box.width);setActive(bisector<number,number>(d=>d).center(xs,v));}} onMouseLeave={()=>setActive(null)}><title>{tr(title)}</title>{y.ticks(5).map(v=><g key={v}><line x1={left} x2={right} y1={y(v)} y2={y(v)} stroke="#dce4d8"/><text x={left-8} y={y(v)+4} textAnchor="end">{fmt(v)}</text></g>)}{x.ticks(width<450?5:10).filter(Number.isInteger).map(v=><text key={v} x={x(v)} y={bottom+22} textAnchor="middle">{v}</text>)}<text x={left} y={15}>{tr(unit)}</text><text x={(left+right)/2} y={266} textAnchor="middle">{tr(xLabel)}</text>{series.map(s=><g key={tr(s.name)}>{Array.from(new Set(s.values.map(p=>p.group??0))).map(group=>{const values=s.values.filter(p=>(p.group??0)===group),curve=line<SeriesPoint>().defined(p=>p.y!==null).x(p=>x(p.x)).y(p=>y(p.y!));return <g key={group}>{s.area&&<path d={area<SeriesPoint>().defined(p=>p.y!==null).x(p=>x(p.x)).y0(y(0)).y1(p=>y(p.y!))(values)??''} fill={s.color} opacity=".12"/>}<path d={curve(values)??''} fill="none" stroke={s.color} strokeWidth={2.5} strokeDasharray={s.dashed?'5 4':undefined}/>{values.filter(p=>p.y!==null).map(p=><circle key={p.x} cx={x(p.x)} cy={y(p.y!)} r={selected===p.x?5:2} fill={s.color}><title>{textAt(p.x)}</title></circle>)}</g>})}</g>)}{selected!==null&&<line x1={x(selected)} x2={x(selected)} y1={top} y2={bottom} stroke="#536651" strokeDasharray="3 3"/>}</svg><div className="d3-legend">{series.map(s=><span key={tr(s.name)}><i style={{background:s.color}}/>{tr(s.name)}{s.dashed?` (${tr('dashed')})`:''}</span>)}</div><p className="d3-tooltip" aria-live="polite">{selected===null?tr('Hover or focus the chart and use arrow keys to inspect values.'):textAt(selected)}</p><details><summary>{tr(title)} · {tr("data")}</summary><div className="table-wrap"><table><thead><tr><th>{tr(xLabel)}</th>{series.map(s=><th key={tr(s.name)}>{tr(s.name)} ({tr(unit)})</th>)}</tr></thead><tbody>{xs.map(v=><tr key={v}><th>{v}</th>{series.map(s=><td key={tr(s.name)}>{s.values.find(p=>p.x===v)?.y==null?'—':fmt(s.values.find(p=>p.x===v)!.y!)}</td>)}</tr>)}</tbody></table></div></details></div>;
}
