import { useState } from 'react';
import type { Game } from './simulation/types';
import { captureAnnualAlternative,rehearseAnnualAlternative,type AnnualActions,type AnnualAlternative } from './simulation/annual-alternatives';
import {useAnnualLanguage} from './annual-language';
export default function AnnualAlternatives({game,actions,onChoose}:{game:Game;actions:AnnualActions;onChoose:(actions:AnnualActions)=>void}){
 const {t,language}=useAnnualLanguage(),[drafts,setDrafts]=useState<(AnnualAlternative|null)[]>([null,null]),[error,setError]=useState('');
 const locked=!!game.linkedSeason&&!game.linkedSeason.settled;const ended=!game.stewardship||game.stewardship.year>(game.linkedSeason?.baseRegion??game.region).stewardship!.years;
 const number=(v:number)=>Math.round(v).toLocaleString(language==='fr'?'fr-CA':'en-CA');
 return <details className="annual-alternatives"><summary>{t('Compare annual alternatives')}</summary><p>{t('One year, same opening forest and budget. Applying an alternative copies choices into the editor; advancing the year remains a separate action.')}</p>
 <div className="annual-alternative-pair">{drafts.map((draft,index)=>{let result:ReturnType<typeof rehearseAnnualAlternative>|null=null,problem='';if(draft)try{result=rehearseAnnualAlternative(game,draft);}catch(e){problem=(e as Error).message;}
 const report=result?.history.at(-1);return <article key={index}><h4>{index===0?'A':'B'}</h4><button disabled={locked||ended} onClick={()=>{try{const value=captureAnnualAlternative(game,actions);setDrafts(drafts.map((d,i)=>i===index?value:d));setError('');}catch(e){setError((e as Error).message);}}}>{t('Save current choices as')} {index===0?'A':'B'}</button>{problem?<p role="status">{t(problem)}</p>:report&&result?<dl className="annual-map-observations"><div><dt>{t('Harvest')}</dt><dd>{number(report.harvest)} m³</dd></div><div><dt>{t('Growth')}</dt><dd>{number(report.growth)} m³</dd></div><div><dt>{t('Standing timber')}</dt><dd>{number(report.closing)} m³</dd></div><div><dt>{t('Closing budget')}</dt><dd>{game.region.currency} {number(result.cash)}</dd></div><div><dt>{t('Landscape habitat')}</dt><dd>{(report.habitat*100).toFixed(1)}%</dd></div><div><dt>{t('Managed habitat')}</dt><dd>{report.managedHabitat==null?'—':`${(report.managedHabitat*100).toFixed(1)}%`}</dd></div></dl>:<p>{t('No saved choices')}</p>}{draft&&<p>{Object.entries(draft.actions).filter(([,a])=>a!=='rest').map(([id,a])=>`${id}: ${t(a)}`).join('; ')||t('All stands rest')}</p>}<button disabled={!result||locked||ended} onClick={()=>{if(draft){try{rehearseAnnualAlternative(game,draft);onChoose(structuredClone(draft.actions));setError('');}catch(e){setError((e as Error).message);}}}}>{t('Use these choices')} {index===0?'A':'B'}</button></article>;})}</div>{error&&<p role="alert">{t(error)}</p>}</details>;
}
