import { useLanguage } from "./i18n";
import {useState} from 'react';
import type {Game} from './simulation/types';
import {recoveredMix,setBucking,buckingProfile} from './simulation/bucking';
import {appraise} from './simulation/appraisal';
import {ProductSymbol} from './OperationalSymbols';
export function BuckingSelect({game,crew,index,onChange}:{game:Game;crew:string;index:number;onChange:(g:Game)=>void}){
 const {t: tr}=useLanguage();const order=game.plan.crews[crew][index];return <label>{tr("Bucking recovery")}<select aria-label={`${crew} ${tr("Stop")} ${index+1} ${tr("Bucking")}`} disabled={game.week>game.region.weeks} value={order.bucking??'standard'} onChange={e=>onChange(setBucking(game,crew,index,e.target.value))}><option value="standard">{tr("Standard recovery")}</option>{Object.entries(game.region.buckingProfiles??{}).map(([id,p])=><option key={id} value={id}>{tr(p.name)}</option>)}</select></label>;}
export default function BuckingDesk({game,standId}:{game:Game;standId:string}){
 const {t: tr}=useLanguage();const [choice,setChoice]=useState('standard'),stand=game.region.stands.find(s=>s.id===standId);if(!stand)return null;const id=choice==='standard'||game.region.buckingProfiles?.[choice]?choice:'standard',mix=recoveredMix(game.region,stand.mix,id),profile=buckingProfile(game.region,id),value=appraise(game,standId,undefined,id);return <section className="panel"><h3>{tr("Bucking and recovery ·")}{" "}{standId}</h3><p>{tr("Choose how existing timber grades become products. Recovery conserves harvested volume and cannot upgrade pulp into sawlogs. These are illustrative processing choices, not measured mill recovery curves. Set the choice on each crew stop to apply it.")}</p><label>{tr("Compare recovery")}<select value={id} onChange={e=>setChoice(e.target.value)}><option value="standard">{tr("Standard recovery")}</option>{Object.entries(game.region.buckingProfiles??{}).map(([key,p])=><option key={key} value={key}>{tr(p.name)}</option>)}</select></label><p>{tr("Productivity ×")}{profile.productivity}{" "}{tr("· direct harvest cost ×")}{profile.cost}</p>{game.region.products.map(p=><p key={p.id}><ProductSymbol product={p}/> · {((mix[p.id]??0)*100).toFixed(1)}{tr("% recovered")}</p>)}<p>{tr("Illustrative lot contribution across access cases:")}{" "}{game.region.currency} {Math.round(value.min).toLocaleString()}{" "}{tr("to")}{" "}{Math.round(value.max).toLocaleString()}{tr(". Demand-capped appraisal includes acquisition and indicative harvest/haul costs, not guaranteed realized profit.")}</p></section>;}
