import { useLanguage } from "./i18n";
import {useState} from 'react';
import {commonValueExperiment,type CommonValueSettings} from './simulation/common-value';
const defaults:CommonValueSettings={seed:421,samples:1000,bidders:5,mean:1000,valueSpread:300,signalNoise:400,rivalShading:.1};
export default function CommonValueExperiment(){
 const {t: tr,language}=useLanguage();
 const [settings,setSettings]=useState<CommonValueSettings>(defaults),[result,setResult]=useState<ReturnType<typeof commonValueExperiment>|null>(null),[error,setError]=useState('');
 const f=(n:number|null)=>n===null?tr("No wins"):n.toLocaleString(language==='fr'?'fr-CA':'en-CA',{maximumFractionDigits:2});
 const dirty=result&&JSON.stringify(result.settings)!==JSON.stringify(settings);
 return <section className="panel common-value-experiment"><h2>{tr("Common-value auction experiment")}</h2><p>{tr("This separate teaching model gives every bidder the same unknown resale value and a different noisy private signal. It does not use campaign seeds, hidden rival bids, lot values or the operating game’s auction rules.")}</p><p>{tr("For each draw, resale value is uniform within mean ± spread. Signals add independent uniform noise within ± the noise bound and are clipped at zero. Rivals bid their signals times one minus rival shading. Highest bid wins and pays its own bid; seeded random priorities break ties. Four policies face the exact same value, signals, rivals and tie priorities.")}</p><div className="form-row">{([['seed','Experiment seed'],['samples','Draws'],['bidders','Total bidders'],['mean','Mean resale value'],['valueSpread','Resale value spread ±'],['signalNoise','Signal noise ±'],['rivalShading','Rival shading fraction']] as const).map(([key,label])=><label key={key}>{tr(label)}<input type="number" value={settings[key]} min={key==='mean'?1:key==='samples'?10:key==='bidders'?2:0} max={key==='seed'?4294967295:key==='samples'?10000:key==='bidders'?12:key==='rivalShading'?1:undefined} step={key==='rivalShading'?.05:1} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})}/></label>)}</div><button onClick={()=>{try{setResult(commonValueExperiment(settings));setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}}}>{tr("Run paired auction experiment")}</button>{error&&<p role="alert">{tr(error)}</p>}
 {result?<><p>{dirty?tr("Inputs changed. Results below still describe the previous run."):tr("Results for the displayed run.")}{" "}{tr("Seed")}{" "}{result.settings.seed}; {result.settings.samples}{" "}{tr("draws;")}{" "}{result.settings.bidders}{" "}{tr("bidders. Values are abstract currency units; profits exclude harvesting, transport and financing costs.")}</p><div className="table-wrap" tabIndex={0} role="region" aria-label={tr("Common-value auction experiment")}><table><thead><tr><th>{tr("Policy")}</th><th>{tr("Win rate")}</th><th>{tr("Profit per auction")}</th><th>{tr("Profit when won")}</th><th>{tr("Overpayment among wins")}</th><th>{tr("Own signal minus value when won")}</th></tr></thead><tbody>{result.rows.map(row=><tr key={row.id}><th>{tr(row.name)}</th><td>{f(row.winRate*100)}% ({row.wins})</td><td>{f(row.expectedProfit)}</td><td>{f(row.conditionalProfit)}</td><td>{row.overpaymentRate===null?tr("No wins"):`${f(row.overpaymentRate*100)}%`}</td><td>{f(row.conditionalSignalError)}</td></tr>)}</tbody></table></div><p>{tr("The winner’s curse is conditional: winning often selects an unusually optimistic signal. Overpayment means paid bid exceeds the shared resale value; losses are not inferred from noisy signals alone. Profit per auction includes zero for losses. Conditional columns use winning auctions only, and show “No wins” when the denominator is zero. Results are Monte Carlo estimates from authored distributions, not calibrated timber values or a guaranteed bidding strategy.")}</p><button onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='common-value-auction-experiment.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>{tr("Export reproducible result")}</button></>:<p role="status">{tr("No experiment has run. Choose assumptions, then compare policies on paired draws.")}</p>}</section>;
}
