import {operatingWorksheetCSV} from './simulation/operating-worksheet';
import { useLanguage } from "./i18n";
import {useState} from 'react';
import {resultsSummary,resultsExplanation} from './simulation/results-summary';
import './results.css';
import type {Game} from './simulation/types';
import {diagnose,debriefMarkdown,worksheetCSV,securedSupplyFrench} from './simulation/debrief';
import {LESSON_KEY,lessons,notesPacket,parseNotes,persistLocal,type LessonNotes} from './simulation/classroom-learning';
function save(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function Debrief({game,onNavigate}:{game:Game;onNavigate:(p:string)=>void}){
 const {t: tr,language}=useLanguage();
 const [initial]=useState(()=>{try{const raw=localStorage.getItem(LESSON_KEY);return {value:raw?parseNotes(raw):{step:0,notes:{}},error:''};}catch{return {value:{step:0,notes:{}},error:'Saved lesson notes could not be read. Import a notes packet to recover them.'};}});
 const [value,setValue]=useState<LessonNotes>(initial.value),[error,setError]=useState(initial.error);
 function update(next:LessonNotes){setValue(next);try{setError(persistLocal(localStorage,LESSON_KEY,notesPacket(next)));}catch{setError('Browser storage unavailable. Export your lesson notes before leaving.');}}
 const [selectedWeek,setSelectedWeek]=useState<number|null>(null);
 const reportIndex=selectedWeek===null?game.history.length-1:game.history.findIndex(h=>h.week===selectedWeek);
 const activeIndex=reportIndex<0?game.history.length-1:reportIndex;
 const report=game.history[activeIndex],findings=diagnose(game,activeIndex),summary=resultsSummary(game);
 const number=(n:number)=>n.toLocaleString(language==='fr'?'fr-CA':'en-CA',{maximumFractionDigits:0});
 const period=tr((game.region.turnDurationWeeks??1)!==1?'turn':'week');
 const evidence=(id:string,text:string)=>language==='fr'&&report?(id==='freshness'?`${Math.round(report.degraded)} m³ déclassés; ${Math.round(report.waste)} m³ expirés.`:id==='service'?`${report.targetHits} engagements respectés sur ${report.targetChecks}.`:id==='secured-supply'?securedSupplyFrench(game):id==='authorization'?text.replace(/^(\S+): (.+)\.$/,(_,stand:string,problem:string)=>`${stand} : ${tr(problem)}.`):tr(text)):tr(text);
 const lesson=lessons[value.step];
 const reflection=lessons.map(l=>`## ${tr(l.title)}\n\n${value.notes[l.id]||tr('No explanation recorded.')}`).join('\n\n');
 return <section className="panel"><h2>{tr("Campaign results & guided debrief")}</h2>
 {summary ? <div className="results-overview"><p><strong>{summary.weeks}{" "}{tr("completed")}{" "}{summary.weeks===1?period:period+'s'}</strong> · {(summary.weeks*(game.region.turnDurationWeeks??1)).toLocaleString(language==='fr'?'fr-CA':'en-CA',{maximumFractionDigits:3})}{" "}{tr("elapsed weeks ·")}{" "}{game.region.name}{" "}{tr("· Scenario")}{" "}{game.weatherId}{" "}{tr("· Seed")}{" "}{game.seed}</p><dl className="results-metrics">
 <div><dt>{tr("Harvested")}</dt><dd>{number(summary.harvested)}{" "}{tr("m³")}</dd></div><div><dt>{tr("Delivered")}</dt><dd>{number(summary.delivered)}{" "}{tr("m³")}</dd></div><div><dt>{tr("Commitment success")}</dt><dd>{summary.servicePercent===null?tr("Not evaluated"):`${number(summary.servicePercent)}% (${summary.hits}/${summary.checks})`}</dd></div><div><dt>{tr("Expired inventory")}</dt><dd>{number(summary.waste)}{" "}{tr("m³")}</dd></div><div><dt>{tr("Emissions / delivered volume")}</dt><dd>{summary.emissionsPerDelivered===null?tr('No deliveries yet'):`${number(summary.emissionsPerDelivered)} kg CO₂/m³`}</dd></div><div><dt>{tr("Last completed turn’s closing cash")}</dt><dd>{game.region.currency} {number(summary.closingCash)}</dd></div></dl></div> : <div className="soft-card" role="status"><h3>{tr("No operating results yet")}</h3><p>{tr("Prepare crew and transport orders, review access and supply, then run the first week. Draft plans and purchases alone do not produce a weekly result.")}</p><button onClick={()=>onNavigate('Overview')}>{tr("Open operations map →")}</button></div>}
 <details className="results-definitions"><summary>{tr("How to read these results")}</summary>{resultsExplanation(game,language).map(text=><p key={text}>{tr(text)}</p>)}</details>
 {report&&<div className="results-week"><label>{tr("Review completed")} {period} <select value={report.week} onChange={e=>setSelectedWeek(Number(e.target.value))}>{game.history.map(h=><option value={h.week} key={h.week}>{period} {h.week}</option>)}</select></label><h3>{period} {report.week}{" "}{tr("· Decision feedback")}</h3>{findings.length?findings.map(d=><div className="soft-card" key={d.id}><h4>{tr(d.title)}</h4>{d.evidence.slice(0,4).map((e,i)=><p key={i}>{evidence(d.id,e)}</p>)}<p>{tr(d.action)}</p></div>):<p>{tr("No access, capacity, ownership, freshness or commitment issues were detected by these diagnostic rules. This is not a complete performance assessment; review output and the operating messages below.")}</p>}<details><summary>{tr("Operating messages (")}{" "}{report.messages.length})</summary>{report.messages.length?<ul>{report.messages.map((message,i)=><li key={i}>{tr(message)}</li>)}</ul>:<p>{tr("No operating messages were recorded for this week.")}</p>}</details></div>}
 <h3>{tr("Guided lesson notebook")}</h3><p>{tr("Six suggested lessons connect the same campaign mechanics. Explanations and your current step are saved in this browser notebook across campaigns; they are not sent to the classroom server. Export or clear the notebook when changing teams.")}</p><div className="button-row">{lessons.map((l,i)=><button key={l.id} aria-pressed={i===value.step} className={i===value.step?'primary':''} onClick={()=>update({...value,step:i})}>{tr("Step")} {i+1}{value.notes[l.id]?.trim()?' ✓':''}</button>)}</div><h3>{value.step+1} · {tr(lesson.title)}</h3><p>{tr(lesson.body)}</p><button onClick={()=>onNavigate(lesson.page)}>{tr("Open")} {tr(lesson.page)} →</button><label style={{display:'block',marginTop:12}}>{tr("Decision and evidence")}<textarea style={{display:'block',width:'100%',minHeight:110}} maxLength={10000} value={value.notes[lesson.id]??''} placeholder={tr("What did your team decide, what evidence supported it, and what would you change? Include scenario, seed and week.")} onChange={e=>update({...value,notes:{...value.notes,[lesson.id]:e.target.value}})}/></label><div className="button-row"><button disabled={value.step===0} onClick={()=>update({...value,step:value.step-1})}>{tr("Previous lesson")}</button><button disabled={value.step===lessons.length-1} onClick={()=>update({...value,step:value.step+1})}>{tr("Next lesson")}</button><button onClick={()=>save('forest-lesson-notes.json',notesPacket(value),'application/json')}>{tr("Export lesson notes")}</button><button onClick={()=>update({step:0,notes:{}})}>{tr("Clear notebook")}</button><label>{tr("Import lesson notes")}<input type="file" accept=".json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(file)try{update(parseNotes(await file.text()));}catch{setError('Invalid lesson notes packet. Existing notes were kept.');}}}/></label></div>{error&&<p role="alert">{tr(error)}</p>}<div className="button-row"><button onClick={()=>save('forest-instructor-debrief.md',`${debriefMarkdown(game,language)}\n\n# ${language==='fr'?'Explications des décisions de l’équipe':'Team decision explanations'}\n\n${reflection}`,'text/markdown')}>{tr("Download instructor debrief with explanations")}</button><button disabled={!game.history.length} onClick={()=>save('forest-operations.csv',operatingWorksheetCSV(game,language),'text/csv;charset=utf-8')}>{tr("Download operating worksheet")}</button><button onClick={()=>save('forest-negotiation-worksheet.csv',worksheetCSV(game,language),'text/csv')}>{tr("Download negotiation worksheet")}</button></div></section>;
}
