import {advancedMessage} from "./advanced-runtime";
import { useLanguage } from "./i18n";
import {useMemo,useState} from 'react';
import type {Game} from './simulation/types';
import {deliverability} from './simulation/deliverability';
export default function DeliverabilityDesk({game}:{game:Game}){
 const {t: tr,language}=useLanguage();
 const result=useMemo(()=>deliverability(game),[game]),[product,setProduct]=useState('');
 const f=(n:number)=>n.toLocaleString(language==='fr'?'fr-CA':'en-CA',{maximumFractionDigits:1});
 return <section className="panel"><h2>{tr("Can this supply reach demand?")}</h2><p>{tr("The current-plan rehearsal accounts for shared operating hours and stock. The site screen below checks each site independently from opening fleet positions; it does not reserve capacity or calculate a joint maximum.")}</p>
 <div className="table-wrap"><table><caption>{tr("Current week forecast against remaining period commitments · m³")}</caption><thead><tr><th>{tr("Product")}</th><th>{tr("Remaining commitment")}</th><th>{tr("Forecast delivery, all channels")}</th><th>{tr("Commitment still unfilled after forecast")}</th></tr></thead><tbody>{result.products.map(p=><tr key={p.product.id}><th>{tr(p.product.name)}</th><td>{f(p.remaining)}</td><td>{p.forecastDelivery===null?tr("Unavailable"):f(p.forecastDelivery)}</td><td>{p.remainingAfterForecast===null?tr("Not resolved"):f(p.remainingAfterForecast)}</td></tr>)}</tbody></table></div>
 <p className="muted">{tr("The gap is calculated at each mill before aggregation, so excess volume at one destination does not fill another mill’s target. This is volume remaining, not the tolerance-based commitment success score.")}</p>{result.mixedReceipts&&<p>{tr("Commitment gaps are not estimated for a plan mixing spot sales, offtake or internal processing: the recorded delivery total combines these channels. Review each commitment in the mill ledger.")}</p>}
 {!result.forecast.report&&<p role="status">{tr("Forecast unavailable:")}{" "}{result.forecast.problems.map(m=>advancedMessage(m,tr)).join(' ')}</p>}
 <label>{tr("Screen product")}<select value={product} onChange={e=>setProduct(e.target.value)}><option value="">{tr("All products")}</option>{game.region.products.map(p=><option value={p.id} key={p.id}>{tr(p.name)}</option>)}</select></label>
 <p>{tr("Only revealed disruptions and forecast weather are used. First-load time includes empty travel, loaded travel and handling. Crew time is the full week less direct relocation; both ignore other assignments here. Do not add these opportunities across sites or products. Regular demand excludes spot, offtake and internal processing opportunities. Roadside stock shown is before the week’s deterioration.")}</p>
 <div className="table-wrap"><table><thead><tr><th>{tr("Site")}</th><th>{tr("Roadside m³")}</th><th>{tr("Crew opportunity")}</th><th>{tr("First-load connections")}</th><th>{tr("Constraints")}</th></tr></thead><tbody>{result.sites.filter(s=>s.owned).map(s=>{const stock=product?(s.roadside[product]??0):Object.values(s.roadside).reduce((n,v)=>n+v,0),connections=s.connections.filter(c=>!product||c.product===product);return <tr key={s.id}><th>{s.id} · {s.name}</th><td>{f(stock)}</td><td>{s.crews.length?<details><summary>{s.crews.length}{" "}{tr("crews with time")}</summary>{s.crews.map(c=><p key={c.id}>{c.name}: {f(c.workHours)}{" "}{tr("h after relocation")}</p>)}</details>:tr("None")}</td><td>{connections.length?<details><summary>{connections.length}{" "}{tr("candidate connections")}</summary>{connections.map((c,i)=><p key={i}>{c.truck} → {c.mill} · {game.region.products.find(p=>p.id===c.product)?.name} · {f(c.firstLoadHours)}{" "}{tr("h · payload")}{" "}{f(c.payload)}{" "}{tr("m³ · demand remaining")}{" "}{f(c.remainingDemand)} m³</p>)}</details>:tr("None for this product")}</td><td>{s.reasons.length?s.reasons.map((reason,i)=><p key={i}>{tr(reason)}</p>):tr("Screening passed; review the current-plan forecast before assigning.")}</td></tr>;})}</tbody></table>{!result.sites.some(s=>s.owned)&&<p>{tr("No secured sites. Acquire timber before planning production and transport.")}</p>}</div>
 </section>;
}
