import { useLanguage } from "./i18n";
import { useState } from "react";
import type { DisclosureView } from "./simulation/disclosure";
export default function DisclosureDesk({value,role,act}:{value:DisclosureView;role:string;act:(action:string,payload:unknown)=>Promise<void>}){
 const {t: tr}=useLanguage();
 const [estimate,setEstimate]=useState(0), [shares,setShares]=useState<Record<string,number>>({}), company=role.startsWith("company");
 const total=Object.values(value.economics).reduce((n,c)=>n+c.standalone-c.pooled,0);
 return <section className="panel"><h3>{tr("Private information experiment ·")}{" "}{" "}{tr(value.phase)}</h3>
 <p>{tr("These server-generated company costs are a separate classroom exercise in arbitrary cost units, not the public handout or campaign ledger. Only your company's numbers and voluntarily shared numbers are returned to you. The instructor can see all numbers.")}</p>
 <p>{tr("Estimate the total savings across all five companies before and after sharing. A company can disclose its own economics during sharing; disclosure is permanent for this exercise. Moving to debrief reveals estimates, not unshared economics.")}</p>
 <div className="table-wrap"><table><thead><tr><th>{tr("Company")}</th><th>{tr("Standalone")}</th><th>{tr("Pooled cost")}</th><th>{tr("Savings")}</th><th>{tr("Disclosure")}</th></tr></thead><tbody>{Object.entries(value.economics).map(([c,e])=><tr key={c}><td>{c}</td><td>{e.standalone}</td><td>{e.pooled}</td><td>{e.standalone-e.pooled}</td><td>{tr(value.shared.includes(c)?"Shared":"Private")}</td></tr>)}</tbody></table></div>
 {company&&value.phase!=="debrief"&&<><label>{tr("Total savings estimate")}<input type="number" value={estimate} onChange={e=>setEstimate(Number(e.target.value))}/></label><button onClick={()=>act("disclosure-estimate",{savings:estimate})}>{tr(value.phase==="private"?"Save before estimate":"Save after estimate")}</button></>}
 {company&&value.phase==="sharing"&&!value.shared.includes(role.slice(7))&&<button onClick={()=>act("disclosure-share",{consent:true})}>{tr("I consent to share my company's costs with this room")}</button>}
 {role==="instructor"&&value.phase!=="debrief"&&<button onClick={()=>act("disclosure-phase",{phase:value.phase==="private"?"sharing":"debrief"})}>{tr(value.phase==="private"?"Open sharing phase":"Open debrief phase")}</button>}
 {role==="instructor"&&value.phase==="sharing"&&<div><h4>{tr("Allocate")}{" "}{total}{" "}{tr("generated savings units")}</h4>{Object.keys(value.economics).map(c=><label key={c}>{tr("Company")} {c}{" "}{tr("savings")}<input type="number" value={shares[c]??total/5} onChange={e=>setShares({...shares,[c]:Number(e.target.value)})}/></label>)}<button onClick={()=>act("disclosure-propose",{shares:Object.fromEntries(Object.keys(value.economics).map(c=>[c,shares[c]??total/5]))})}>{tr("Propose this savings agreement")}</button></div>}
 {(value.offers??[]).map(o=><div key={o.id}><h4>{tr("Offer")} {o.id} · {tr(o.status)}</h4><p>{Object.entries(o.shares).map(([c,n])=>`${tr("Company")} ${c}: ${n} ${tr("units")}`).join(" · ")}</p><p>{tr("Accepted by:")}{" "}{o.accepted.join(", ")||tr("none")}{" "}{tr(". Realized exercise savings:")}{" "}{o.status==="agreed"?Object.values(o.shares).reduce((a,b)=>a+b,0):0}{" "}{tr("units.")}</p>{company&&value.phase==="sharing"&&o.status==="proposed"&&!o.accepted.includes(role.slice(7))&&<><button onClick={()=>act("disclosure-respond",{id:o.id,accept:true})}>{tr("Accept my allocation")}</button><button onClick={()=>act("disclosure-respond",{id:o.id,accept:false})}>{tr("Reject this offer")}</button></>}</div>)}
 <p className="muted">{tr("A proposed allocation reveals offered savings and their total, not undisclosed company cost pairs. Only unanimous authenticated acceptance realizes the exercise savings. Rejection leaves the independent baseline (zero savings). These exercise consequences do not change campaign cash.")}</p>
 <h4>{tr("Before / after estimates")}</h4><div className="table-wrap"><table><thead><tr><th>{tr("Company")}</th><th>{tr("Before")}</th><th>{tr("After")}</th><th>{tr("Change")}</th></tr></thead><tbody>{Object.entries(value.estimates).map(([c,e])=><tr key={c}><td>{c}</td><td>{e.before??tr("Not submitted")}</td><td>{e.after??tr("Not submitted")}</td><td>{e.before!==undefined&&e.after!==undefined?e.after-e.before:"—"}</td></tr>)}</tbody></table></div>
 {value.phase==="debrief"&&<p>{tr("Which disclosures changed your estimate? Did unshared information make agreement harder? Missing estimates are not zero. Compare prediction accuracy with the instructor's total, if the instructor chooses to explain it.")}</p>}
 </section>;
}
