import { useLanguage } from "./i18n";
import {useEffect,useState} from 'react';
import type {Game} from './simulation/types';
import type {DraftPlanOptions} from './simulation/engine';
export default function DraftOptions({game,onDraft}:{game:Game;onDraft:(options:DraftPlanOptions)=>void}) {
 const {t: tr}=useLanguage();
 const key=`forest-draft-options:${game.region.id}`;
 const [saved]=useState(()=>{try{const v=JSON.parse(localStorage.getItem(key)??'{}');return v&&typeof v==='object'?v:{};}catch{return {};}});
 const [bucking,setBucking]=useState(typeof saved.bucking==='string'&&Object.hasOwn(game.region.buckingProfiles??{},saved.bucking)?saved.bucking:'standard');
 const [harvestFraction,setHarvestFraction]=useState([1,.75,.5,.25].includes(saved.harvestFraction)?saved.harvestFraction:1);
 const [treatment,setTreatment]=useState(typeof saved.treatment==='string'&&Object.hasOwn(game.region.treatments??{},saved.treatment)?saved.treatment:'final');
 const [commitmentAware,setCommitmentAware]=useState(saved.commitmentAware===true);
 const [salesPolicy,setSalesPolicy]=useState<NonNullable<DraftPlanOptions["salesPolicy"]>>(['margin','contract-first','penalty-aware'].includes(saved.salesPolicy)?saved.salesPolicy:'margin');
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify({bucking,harvestFraction,treatment,commitmentAware,salesPolicy}));}catch{/* Preferences are optional when storage is unavailable. */}},[key,bucking,harvestFraction,treatment,commitmentAware,salesPolicy]);
 return <fieldset><legend>{tr("Forecast draft strategy")}</legend><label>{tr("Harvest effort")} <select value={harvestFraction} onChange={e=>setHarvestFraction(Number(e.target.value))}>{[1,.75,.5,.25].map(v=><option key={v} value={v}>{v*100}%</option>)}</select></label><label>{tr("Treatment")} <select value={treatment} onChange={e=>setTreatment(e.target.value)}>{Object.entries(game.region.treatments ?? {final:{name:'Final harvest'}}).map(([id,t])=><option key={id} value={id}>{tr(t.name)}</option>)}</select></label> {game.region.buckingProfiles && <label>{tr("Bucking")} <select value={bucking} onChange={e=>setBucking(e.target.value)}><option value="standard">{tr("Standard recovery")}</option>{Object.entries(game.region.buckingProfiles).filter(([id])=>id!=="standard").map(([id,p])=><option key={id} value={id}>{tr(p.name)}</option>)}</select></label>} <label><input type="checkbox" checked={commitmentAware} onChange={e=>setCommitmentAware(e.target.checked)}/>{" "}{tr("Cap dispatch at commitments")}</label><label>{tr("Sales priority")}{" "}<select value={salesPolicy} onChange={e=>setSalesPolicy(e.target.value as typeof salesPolicy)}><option value="margin">{tr("Net transport margin")}</option><option value="contract-first">{tr("Contracts first")}</option><option value="penalty-aware">{tr("Include avoided shortfall penalties")}</option></select></label><p className="muted">{tr("Uses forecast access and selected treatment and bucking productivity and recovery. The optional cap reserves whole loads within remaining monthly targets; small remainders may need manual dispatch. Ranking uses net transport margin per hour and the selected contract policy. Avoided penalties affect advice only, never sales revenue. The cap does not guarantee better service or profit.")}</p><p className="muted">{tr("Drafting schedules existing secured timber; it does not buy lots or place auction bids. Review Forest & timber or the planning advisor’s acquisition comparison before secured supply runs out.")}</p><p className="muted">{tr("Harvest effort scales drafted crew hours. Truck orders stay unchanged; rehearse the reduced plan to check stock and delivery. Lower effort can reduce waste but may miss commitments.")}</p><button disabled={game.week>game.region.weeks} onClick={()=>onDraft({treatment,bucking,commitmentAware,salesPolicy,harvestFraction})}>{tr("Draft with these choices")}</button></fieldset>;
}
