import { useLanguage } from "./i18n";
import {useState} from 'react';
import './teaching-interactive.css';
import {eightCompanies,newEightRound,parseEight,chooseEightRule,acceptEight,revealEight,eightDisclosure,eightPrintPacket,standaloneEight,type EightRound,type EightRule} from './simulation/eight-company';
const KEY='forest-eight-company-round-v1';
export default function EightCompanyExercise(){
 const {t: tr,language}=useLanguage();
 const [initial]=useState(()=>{try{const raw=localStorage.getItem(KEY);return {state:raw?parseEight(raw):newEightRound(),error:''};}catch{return {state:newEightRound(),error:'Saved exercise could not be read. A fresh local round is shown.'};}}),[state,setState]=useState<EightRound>(initial.state),[error,setError]=useState(initial.error),[reset,setReset]=useState(false);
 function update(next:EightRound){setState(next);try{localStorage.setItem(KEY,JSON.stringify(next));setError('');}catch{setError('Browser storage is unavailable. Export the round before leaving.');}}
 function download(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const data=eightDisclosure(state),f=(n:number)=>n.toLocaleString(language==='fr'?'fr-CA':'en-CA',{maximumFractionDigits:2});
 function printPacket(){
  if(language==='en')return eightPrintPacket(state);
  const lines=[`Exercice de huit entreprises · manche ${state.round}`,'Coefficients pédagogiques générés en unités de coût abstraites; distincts des données originales et des finances de la campagne. Les accords locaux sur appareil partagé ne sont pas des signatures authentifiées.',`Règle : ${tr(state.rule==='equal'?'Equal savings per member':'Savings proportional to standalone cost')}. Accords : ${state.accepted.join(', ')||tr('None')}.`,state.revealed?'Coalitions divulguées; règle figée.':'Coalitions plus grandes non divulguées.','Économies par paire',...data.pairs.map(p=>`${p.members.join(' + ')} : ${f(p.savings)}`)];
  if(data.large)lines.push('Répartition divulguée',`Économies de la grande coalition : ${f(data.large.grand)}`,...Object.entries(data.large.allocation).map(([id,n])=>`Entreprise ${id} : ${f(n)} économies`),'Négociation par exclusion',...data.large.exclusions.map(e=>`Exclure ${e.excluded} : économies ${f(e.savings)}; écart ${f(e.delta)}; membres gagnants : ${e.gainingMembers.join(', ')||tr('None')}.`),`Sous-coalitions bloquantes : ${data.large.blocking.length}.`);
  lines.push('Réflexion',state.reflection||'Aucune réflexion enregistrée.',tr('Why did you accept the rule? Who benefits from exclusion? Would you choose differently next round?'));
  const text=lines.join('\n\n').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
  return `<!doctype html><html lang="fr"><meta charset="utf-8"><title>Réflexion — huit entreprises</title><style>body{max-width:850px;margin:32px auto;padding:0 20px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:15px/1.6 system-ui}</style><body><pre>${text}</pre></body></html>`;
 }
 const fr=language==='fr';
 return <section className="panel"><h2>{tr("Eight companies · agree before disclosure")}</h2><p className="lab-scope" data-scope="separate"><strong>{fr?'Exercice distinct':'Separate exercise'}</strong><span>{fr?'Unités de coût générées; aucun lien avec la campagne ni avec les données à quatre ou cinq entreprises.':'Generated cost units; not linked to the campaign or the four/five-company data.'}</span></p><p className="lab-lead">{fr?`Manche ${state.round}. Chaque entreprise accepte une règle de partage avant que les résultats des grandes coalitions soient révélés.`:`Round ${state.round}. Every company accepts a sharing rule before the larger coalition results are revealed.`}</p><details className="lab-more"><summary>{fr?'Déroulement de la manche':'How this round works'}</summary><p>{tr("Round")}{" "}{state.round}{tr(". This is a local pass-and-play exercise: pass the device to each representative to record acceptance. Confirmations are not authenticated online decisions. Generated teaching coefficients use abstract cost units, separate from the original four/five-company source data and campaign finances.")}</p><p>{tr("Initially only standalone costs and pair savings are shown. Agree on how to divide savings before revealing larger coalition results. This is staged classroom disclosure, not protection against inspecting local source code.")}</p><p>{tr("Changing the rule before disclosure clears every acceptance. After disclosure it is frozen until a new round.")}</p></details>
 <h3 className="lab-step-heading"><span className="lab-step-number">1</span>{fr?'Choisir la règle de partage':'Choose the sharing rule'}</h3><label>{tr("Sharing rule")}<select disabled={state.revealed} value={state.rule} onChange={e=>update(chooseEightRule(state,e.target.value as EightRule))}><option value="equal">{tr("Equal savings per member")}</option><option value="standalone">{tr("Savings proportional to standalone cost")}</option></select></label>
 <h3 className="lab-step-heading"><span className="lab-step-number">2</span>{fr?'Enregistrer l’accord de chaque entreprise':'Record each company’s acceptance'} <small>{state.accepted.length} / 8</small></h3><div className="lab-choice-grid">{eightCompanies.map(id=><button key={id} disabled={state.revealed} aria-pressed={state.accepted.includes(id)} onClick={()=>update(acceptEight(state,id,!state.accepted.includes(id)))}><strong>{tr("Company")} {id}</strong><small>{tr("Standalone cost")}: {standaloneEight(id)}</small><span>{state.accepted.includes(id)?tr("Accepted · withdraw"):tr("Accept sharing rule")}</span></button>)}</div>
 <details className="lab-more"><summary>{tr("Pairwise savings · 28 pairs")}</summary><div className="table-wrap"><table><thead><tr><th>{tr("Companies")}</th><th>{tr("Savings")}</th></tr></thead><tbody>{data.pairs.map(p=><tr key={p.members.join('-')}><th>{p.members.join(' + ')}</th><td>{f(p.savings)}</td></tr>)}</tbody></table></div></details>
 <h3 className="lab-step-heading"><span className="lab-step-number">3</span>{fr?'Révéler les grandes coalitions':'Reveal the larger coalitions'}</h3>{!state.revealed&&<><p>{state.accepted.length}{tr("/8 companies have accepted. No larger coalition totals are included in the current view or reflection export.")}</p><button disabled={state.accepted.length!==8} onClick={()=>update(revealEight(state))}>{tr("Freeze rule and reveal larger coalitions")}</button></>}
 {data.large&&<><h3>{tr("Revealed coalition results")}</h3><p>{tr("Grand coalition savings:")}{" "}{f(data.large.grand)}{" "}{tr("cost units. Generated pair benefits are reduced by coordination costs for larger groups; more participants do not automatically create more savings.")}</p><div className="table-wrap"><table className="stack-table"><thead><tr><th>{tr("Company")}</th><th>{tr("Allocated savings")}</th><th>{tr("Allocated cost")}</th></tr></thead><tbody>{eightCompanies.map(id=><tr key={id}><th>{id}</th><td data-label={tr("Allocated savings")}>{f(data.large!.allocation[id])}</td><td data-label={tr("Allocated cost")}>{f(standaloneEight(id)-data.large!.allocation[id])}</td></tr>)}</tbody></table></div><h3>{tr("Exclusion bargaining")}</h3><p>{tr("Compare each seven-company alternative under the same frozen rule. A larger total gain does not guarantee that every remaining company receives more; excluded companies keep their standalone outside option.")}</p><div className="table-wrap"><table className="stack-table"><thead><tr><th>{tr("Excluded company")}</th><th>{tr("Coalition savings")}</th><th>{tr("Change vs grand coalition")}</th><th>{tr("Remaining companies gaining")}</th></tr></thead><tbody>{data.large.exclusions.map(e=><tr key={e.excluded}><th>{e.excluded}</th><td data-label={tr("Coalition savings")}>{f(e.savings)}</td><td data-label={tr("Change vs grand coalition")}>{f(e.delta)}</td><td data-label={tr("Remaining companies gaining")}>{e.gainingMembers.join(', ')||tr("None")}</td></tr>)}</tbody></table></div><details className="lab-more"><summary>{tr("Blocking coalition analysis ·")}{" "}{data.large.blocking.length}{" "}{tr("alternatives")}</summary><p>{tr("A positive gap means a subgroup can obtain more total savings than its grand-coalition allocation. This permits a redistribution making members better off; it does not guarantee the frozen sharing rule does so.")}</p>{data.large.blocking.length?data.large.blocking.map(b=><p key={b.members.join('-')}>{b.members.join(' + ')}: {f(b.gap)}{" "}{tr("additional cost units available.")}</p>):<p>{tr("No proper coalition blocks this allocation in the generated model.")}</p>}</details></>}
 <details className="lab-step" open={state.revealed}><summary><span className="lab-step-number">4</span>{fr?'Réflexion, exportation et nouvelle manche':'Reflection, export and new round'}</summary><label style={{display:'block'}}>{tr("Team reflection")}<textarea maxLength={6000} style={{display:'block',width:'100%',minHeight:100}} value={state.reflection} onChange={e=>update({...state,reflection:e.target.value})} placeholder={tr("Why did you accept the rule? Who benefits from exclusion? Would you choose differently next round?")}/></label><div className="button-row"><button onClick={()=>download('eight-company-reflection.html',printPacket(),'text/html')}>{tr("Export printable reflection packet")}</button><button onClick={()=>download('eight-company-round.json',JSON.stringify(state,null,2),'application/json')}>{tr("Export saved round")}</button><label>{tr("Import saved round")}<input type="file" accept=".json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(file)try{update(parseEight(await file.text()));}catch{setError('Invalid round. Existing work was kept.');}}}/></label><button onClick={()=>setReset(true)}>{tr("Start a new round")}</button></div>{reset&&<p role="status">{tr("Starting a new round clears this round’s decisions and changes the generated coefficients. Export first to keep them.")}{" "}<button onClick={()=>{update(newEightRound(state.round>=1000000?1:state.round+1));setReset(false);}}>{tr("Start fresh round")}</button> <button onClick={()=>setReset(false)}>{tr("Keep current round")}</button></p>}</details>{error&&<p role="alert">{tr(error)}</p>}</section>;
}
