import { useLanguage } from "./i18n";
import type {Game} from './simulation/types';
export function FacilityTransferDesk({game,onChange,editable=true}:{game:Game;onChange:(g:Game)=>void;editable?:boolean}) {
 const {t: tr}=useLanguage();
 editable=editable&&game.week<=game.region.weeks;
 const links=game.region.facilityTransfers??[],orders=game.plan.facilityTransfers??[];
 const update=(next:typeof orders)=>{const g=structuredClone(game);g.plan.facilityTransfers=next;g.plan.ready.transport=false;onChange(g);};
 return <section className="panel"><h3>{tr("Facility transfers")}</h3><p>{tr("Forest deliveries run first. Transfers use remaining truck hours and existing output stock, before this week’s processing. Internal transfers earn no sales revenue. Quantities are input-equivalent m³.")}</p>{!links.length?<p>{tr("No transfer mappings configured for this region.")}</p>:<><button disabled={!editable||game.week>game.region.weeks} onClick={()=>update([...orders,{link:links[0].id,truck:game.region.trucks[0].id,loads:1}])}>{tr("Add facility transfer")}</button>{orders.map((o,i)=><div key={i} className="form-row"><label>{tr("Output route")}<select disabled={!editable} value={o.link} onChange={e=>update(orders.map((v,j)=>j===i?{...v,link:e.target.value}:v))}>{links.map(l=><option key={l.id} value={l.id}>{game.region.mills.find(m=>m.id===l.source)?.name} / {l.output} → {game.region.mills.find(m=>m.id===l.target)?.name} / {l.input}</option>)}</select></label><label>{tr("Truck")}<select disabled={!editable} value={o.truck} onChange={e=>update(orders.map((v,j)=>j===i?{...v,truck:e.target.value}:v))}>{game.region.trucks.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>{tr("Loads")}<input disabled={!editable} type="number" min={1} max={100} value={o.loads} onChange={e=>update(orders.map((v,j)=>j===i?{...v,loads:Math.max(1,Math.min(100,Math.floor(Number(e.target.value)||1)))}:v))}/></label><button disabled={!editable} onClick={()=>update(orders.filter((_,j)=>i!==j))}>{tr("Remove transfer")}</button></div>)}</> }</section>;
}
