import type { LedgerEntry, RegionDefinition } from "./simulation/types";
// Display labels only; saved ledger category identifiers remain stable.
const labels: Record<string, string> = {
  "purchase": "Timber purchases",
  "refusal": "Lot refusal charges",
  "roads": "Road improvements",
  "recovery": "Disruption recovery",
  "mobilization": "Fleet positioning",
  "royalty": "Harvest royalties",
  "stumpage": "BC Crown stumpage",
  "post-harvest": "Post-harvest obligations",
  "production": "Harvest production",
  "haul": "Timber transport",
  "sales": "Ordinary timber sales",
  "spot-sales": "Spot timber sales",
  "offtake-sales": "Partner contract sales",
  "finished-sales": "Finished product sales",
  "overhead": "Operating overhead",
  "fleet": "Fleet costs",
  "storage": "Inventory storage",
  "processing": "Mill processing",
  "facility-haul": "Intermill transport",
  "reciprocal-haul": "Reciprocal transport",
  "cooperation": "Cooperation payments",
  "interest": "Debt interest",
  "target": "Commitment bonuses and shortfalls",
  "shortfall": "Commitment shortfall charges",
  "terminal": "Closing inventory charges",
  "offtake-shortfall": "Partner contract shortfall charges"
};
export const ledgerCategoryLabel = (category: string): string => labels[category] ?? category;

/** Recognize only descriptions generated by this region; preserve imported prose. */
export function ledgerDescription(entry: LedgerEntry, region: RegionDefinition, tr: (text: string) => string): string {
  if (entry.category === 'target') {
    for (const mill of region.mills) for (const product of region.products) {
      const prefix = `${mill.name} / ${product.id}`;
      for (const outcome of ['commitment achieved', 'shortfall']) {
        if (entry.description === `${prefix} ${outcome}`) {
          return `${mill.name} / ${tr(product.name)} · ${tr(outcome === 'shortfall' ? 'Commitment shortfall' : 'Commitment achieved')}`;
        }
      }
    }
  }
  return tr(entry.description);
}
