import { ledgerCategoryLabel } from "./ledger-labels";
import { useLanguage } from "./i18n";
import type {Game} from './simulation/types';
import {lotProfitability,lotProfitabilityCSV} from './simulation/lot-profitability';
export default function LotProfitability({game}:{game:Game}){
 const {t: tr,language}=useLanguage();
 const result=lotProfitability(game),f=(n:number)=>n.toLocaleString(language==='fr'?'fr-CA':'en-CA',{maximumFractionDigits:2});
 function download(){const url=URL.createObjectURL(new Blob([lotProfitabilityCSV(game)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='forest-lot-cash-contribution.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="panel"><h2>{tr("Realized lot cash contribution")}</h2><p>{tr("Recorded receipts less paid costs, in")}{" "}{game.region.currency}{tr(". Includes completed weeks and purchases made in the current planning week. This is a cash contribution, not inventory-adjusted accounting profit.")}</p><p>{tr("Only ledger entries explicitly linked to a lot are attributed. Held timber, roadside stock and internal mill transfers create no assumed revenue. Shared overhead, mill processing and legacy entries without a lot link remain below; they are not spread across lots.")}</p>
 {!result.entries?<p role="status">{tr("No cash transactions have been recorded. Secure timber or run a week to begin the record.")}</p>:!result.lots.length?<p role="status">{tr("No transactions in this save carry a lot identifier yet. The recorded cash is preserved in the unallocated table; new linked transactions will appear here.")}</p>:<div className="table-wrap" tabIndex={0} role="region" aria-label={tr("Lot contribution before unallocated costs and receipts")}><table><caption>{tr("Lot contribution before unallocated costs and receipts")}</caption><thead><tr><th>{tr("Lot")}</th><th>{tr("Receipts")}</th><th>{tr("Paid costs")}</th><th>{tr("Net cash contribution")}</th><th>{tr("Evidence")}</th></tr></thead><tbody>{result.lots.map(row=><tr key={row.id}><th>{row.id} · {tr(row.name)}</th><td>{f(row.receipts)}</td><td>{f(row.costs)}</td><td>{f(row.net)}</td><td><details><summary>{row.entries}{" "}{tr("ledger entries")}</summary>{Object.entries(row.categories).map(([category,amount])=><p key={tr(ledgerCategoryLabel(category))}>{tr(ledgerCategoryLabel(category))}: {f(amount)} {game.region.currency}</p>)}</details></td></tr>)}</tbody></table></div>}
 {Object.keys(result.unallocated).length>0&&<div className="table-wrap" tabIndex={0} role="region" aria-label={tr("Unallocated and unattributed cash")}><table><caption>{tr("Unallocated and unattributed cash")}</caption><thead><tr><th>{tr("Category")}</th><th>{tr("Receipts")}</th><th>{tr("Paid costs")}</th><th>{tr("Net cash")}</th></tr></thead><tbody>{Object.entries(result.unallocated).map(([category,row])=><tr key={tr(ledgerCategoryLabel(category))}><th>{tr(ledgerCategoryLabel(category))}</th><td>{f(row.receipts)}</td><td>{f(row.costs)}</td><td>{f(row.net)}</td></tr>)}</tbody></table></div>}
 <p>{tr("Attributed")}{" "}{f(result.attributedNet)}{" "}{tr("+ unallocated")}{" "}{f(result.unallocatedNet)}{" "}{tr("= recorded ledger change")}{" "}{f(result.ledgerNet)} {game.region.currency}.</p>{Math.abs(result.reconciliationDifference)>.01&&<p role="status">{tr("The cash balance differs from the recorded ledger by")}{" "}{f(result.reconciliationDifference)} {game.region.currency}{tr(". This save does not contain a fully reconciling cash history; the difference has not been assigned to any lot.")}</p>}<button onClick={download} disabled={!result.entries}>{tr("Export lot cash contribution CSV")}</button></section>;
}
