import { operatingPayload } from './simulation/operations-profile';
import {reciprocalDispatchRestriction} from './simulation/reciprocal';
import ReciprocalService from "./ReciprocalService";
import {standSupportsProduct} from './simulation/intake-products';
import { useLanguage } from "./i18n";
import {useEffect,useMemo,useState} from 'react';
import type {Game} from './simulation/types';
import {month,stockAt,sum} from './simulation/engine';
import {forecastOutcome,supplyBalance} from './simulation/planning';
import {weatherAt,canAccess,route} from './simulation/routing';
import {operatingRegion,activeDisruptions} from './simulation/disruptions';
import {ProductSymbol,EquipmentStatus} from './OperationalSymbols';
export type MapRole='purchase'|'production'|'transport';
export default function MapRolePanel({game,role,setRole,product,setProduct,zone,setZone,selected,select,onChange,onInspect,accessibleOnly,setAccessibleOnly}:{game:Game;role:MapRole;setRole:(r:MapRole)=>void;product:string;setProduct:(s:string)=>void;zone:string;setZone:(s:string)=>void;selected:string;select:(s:string)=>void;onChange:(g:Game)=>void;onInspect:(kind:'crew'|'truck',id:string)=>void;accessibleOnly:boolean;setAccessibleOnly:(v:boolean)=>void}) {
 const {t: tr,language}=useLanguage();
 const f=(n:number)=>Math.round(n).toLocaleString(language==='fr'?'fr-CA':'en-CA');
 const r=game.region,done=game.week>r.weeks;
 const [selectedTruck,setTruck]=useState(r.trucks[0]?.id??''),[selectedMill,setMill]=useState(r.mills[0]?.id??''),[loads,setLoads]=useState(1),[notice,setNotice]=useState('');
 const truck=r.trucks.some(t=>t.id===selectedTruck)?selectedTruck:r.trucks[0]?.id??'';
 const mill=r.mills.some(m=>m.id===selectedMill)?selectedMill:r.mills[0]?.id??'';
 useEffect(()=>setNotice(''),[game.week]);
 const preview=useMemo(()=>forecastOutcome(game),[game]);
 const balance=useMemo(()=>supplyBalance(game),[game]);
 const rows=r.stands.filter(s=>(!accessibleOnly||(game.stands.find(t=>t.id===s.id)?.owned&&canAccess(s.terrain,weatherAt(game,true)[s.zone])))&&(!zone||s.zone===zone)&&(!product||standSupportsProduct(game,s.id,product)));
 const weather=weatherAt(game,true),op=operatingRegion(game);
 const chosen=r.stands.find(s=>s.id===selected),vehicle=r.trucks.find(t=>t.id===truck),destination=r.mills.find(m=>m.id===mill);
 const haulProduct=product||r.products.find(p=>destination?.prices[p.id]!==undefined)?.id||'';
 const restriction=chosen?reciprocalDispatchRestriction(game,{stand:selected,mill,product:haulProduct},Math.min(stockAt(game,selected)[haulProduct]??0,(vehicle?.payload??0)*loads)):null;
 const fixedDestination=restriction?.reason==='fixed';
 const access=chosen&&vehicle&&destination&&route(op,game.truckPositions[truck],chosen.node,weather,game.improvedRoads,{kind:'truck',id:truck,product:haulProduct,payloadM3:0})&&route(op,chosen.node,destination.node,weather,game.improvedRoads,{kind:'truck',id:truck,product:haulProduct,payloadM3:operatingPayload(r,truck,haulProduct)})&&!activeDisruptions(game).some(e=>(e.kind==='truck'&&e.target===truck)||(e.kind==='mill'&&e.target===mill));
 function changeQueue(kind:'crew'|'truck',id:string,index:number,remove:boolean){const next=structuredClone(game);const queue=kind==='crew'?next.plan.crews[id]:next.plan.trucks[id];if(remove)queue.splice(index,1);else if(index>0)[queue[index-1],queue[index]]=[queue[index],queue[index-1]];next.plan.ready={purchase:false,production:false,transport:false};onChange(next);}
 return <section className="map-role-panel" aria-label={tr("Map planning workbench")}>
 <div className="role-tabs" aria-label={tr("Planning role")}>{(['purchase','production','transport'] as const).map(v=><button key={v} aria-pressed={role===v} onClick={()=>setRole(v)}>{v==='purchase'?tr("Purchase"):v==='production'?tr("Production"):tr("Transport")}</button>)}</div>
 <div className="workbench-filters"><label>{tr("Product")}<select value={product} onChange={e=>setProduct(e.target.value)}><option value="">{tr("All products")}</option>{r.products.map(p=><option key={p.id} value={p.id}>{tr(p.name)}</option>)}</select></label><label>{tr("Zone")}<select value={zone} onChange={e=>setZone(e.target.value)}><option value="">{tr("All zones")}</option>{r.zones.map(z=><option key={z.id} value={z.id}>{tr(z.name)}</option>)}</select></label><button onClick={()=>{setProduct('');setZone('');setAccessibleOnly(false);}}>{tr("Reset filters")}</button></div>
 <label className="access-filter"><input type="checkbox" checked={accessibleOnly} onChange={e=>setAccessibleOnly(e.target.checked)}/> {tr("Secured sites with forecast terrain access")}</label>
 {!rows.some(s=>s.id===selected)&&<p className="notice" role="status">{tr("Selected site")} {selected} {tr("is outside these filters.")} <button onClick={()=>{setProduct('');setZone('');setAccessibleOnly(false);}}>{tr("Reveal selected site")}</button></p>}
 <details open><summary>{tr("Forecast and access ·")} {(r.turnDurationWeeks??1)!==1?tr('Turn').toLowerCase():tr('Week').toLowerCase()} {Math.min(game.week,r.weeks)}</summary>{done?<p>{tr("Season complete — no future forecast.")}</p>:<div className="table-wrap"><table className="forecast-grid"><caption>{tr("Forecast only · future actual weather is not shown")}</caption><thead><tr><th>{tr("Zone")}</th>{Array.from({length:Math.min(4,Math.max(0,r.weeks-game.week+1))},(_,i)=><th key={i}>{tr((r.turnDurationWeeks??1)!==1?'Turn':'Week').charAt(0)}{game.week+i}</th>)}</tr></thead><tbody>{r.zones.filter(z=>!zone||z.id===zone).map(z=><tr key={z.id}><th>{tr(z.name)}</th>{Array.from({length:Math.min(4,Math.max(0,r.weeks-game.week+1))},(_,i)=>{const w=weatherAt(game,true,game.week+i)[z.id];return <td key={i} data-weather={w}>{w==='frozen'?tr("Winter"):w==='thaw'?tr("Thaw"):w==='wet'?tr("Wet"):tr("Normal")}</td>;})}</tr>)}</tbody></table></div>}<p className="muted">{tr("Terrain access is only one constraint. Road closures, relocation, stock and receiving capacity are checked in the forecast rehearsal.")}</p></details>
 <details open><summary>{tr("Linked")} {role==='purchase'?tr("timber market"):tr("supply areas")} · {rows.length} {tr("sites")}</summary><div className="workbench-sites table-wrap"><table><thead><tr><th>{tr("Site")}</th><th>{role==='purchase'?tr("Supply"):tr("Roadside m³")}</th><th>{tr("Terrain")}</th></tr></thead><tbody>{rows.map(s=>{const state=game.stands.find(x=>x.id===s.id)!;return <tr key={s.id} aria-selected={selected===s.id}><td><button aria-pressed={selected===s.id} onClick={()=>select(s.id)}>{s.id} · {s.name}</button></td><td>{role==='purchase'?(state.refused?tr("Refused"):state.owned?tr("Secured"):s.supply==='auction'?(s.auctionWeek===game.week?tr("Auction open"):(s.auctionWeek??0)>game.week?tr("Upcoming auction"):tr("Auction closed")):tr(s.supply)):f(product?(stockAt(game,s.id)[product]??0):sum(stockAt(game,s.id)))}</td><td>{canAccess(s.terrain,weather[s.zone])?tr("Open"):tr("Restricted")}</td></tr>;})}</tbody></table>{!rows.length&&<p>{tr("No sites match these filters.")}</p>}</div></details>
 {role!=='purchase'&&<details open><summary>{role==='production'?tr("Crew queues"):tr("Truck queues")}</summary>{(role==='production'?r.crews:r.trucks).map(resource=>{const kind=role==='production'?'crew':'truck';const queue=kind==='crew'?game.plan.crews[resource.id]:game.plan.trucks[resource.id];return <article className="workbench-resource" key={resource.id}><button onClick={()=>onInspect(kind,resource.id)}>{resource.name}</button> <EquipmentStatus game={game} kind={kind} id={resource.id}/><ol>{queue?.map((o,i)=><li key={i}><button onClick={()=>select(o.stand)}>{o.stand} · {'hours' in o?`${o.hours} h`:`${o.loads} ${tr("loads")} → ${o.mill}`}</button><button disabled={done||i===0} aria-label={language==='fr'?`Avancer l’ordre ${i+1} de ${resource.name}`:`Move ${resource.name} order ${i+1} earlier`} onClick={()=>changeQueue(kind,resource.id,i,false)}>↑</button><button disabled={done} aria-label={language==='fr'?`Retirer l’ordre ${i+1} de ${resource.name}`:`Remove ${resource.name} order ${i+1}`} onClick={()=>changeQueue(kind,resource.id,i,true)}>{tr("Remove")}</button></li>)}</ol>{!queue?.length&&<small>{tr("No stand orders.")} {kind==='crew'?tr("Select a secured site to assign hours."):tr("Select a site and add a haul below.")}</small>}{kind==='truck'&&game.plan.facilityTransfers?.filter(o=>o.truck===resource.id).map((o,i)=><p key={i}>{tr("Facility transfer ·")} {o.link} · {o.loads} {tr("loads")}</p>)}{kind==='truck'&&game.plan.reciprocal?.filter(o=>o.truckA===resource.id||o.truckB===resource.id).map((o,i)=>{const pair=r.reciprocalPairs?.find(p=>p.id===o.pair);if(!pair)return null;const stand=o.truckA===resource.id?pair.standA:pair.standB,destination=o.truckA===resource.id?pair.millB:pair.millA;return <p className="workbench-reciprocal-order" key={`reciprocal-${i}`}>{tr("Reciprocal delivery")} · {pair.name} · <button onClick={()=>select(stand)}>{stand} → {destination}</button> · {o.loads} {tr("loads")}</p>;})}</article>;})}</details>}
 {role!=='purchase'&&(r.reciprocalPairs??[]).filter(pair=>[pair.standA,pair.standB].includes(selected)&&(!product||pair.product===product)).map(pair=><details key={`service-${pair.id}`}><summary>{tr("Supply agreement at selected site")} · {pair.name}</summary><ReciprocalService game={game} pair={pair}/>{role==='transport'&&!done&&<button onClick={()=>{setMill(selected===pair.standA?pair.millA:pair.millB);setProduct(pair.product);}}>{tr("Plan own-mill delivery")} · {selected} → {selected===pair.standA?pair.millA:pair.millB}</button>}</details>)}
 {role==='transport'&&<fieldset disabled={done}><legend>{tr("Haul from selected site ·")} {selected}</legend><label>{tr("Truck")}<select value={truck} onChange={e=>setTruck(e.target.value)}>{r.trucks.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>{tr("Destination")}<select value={mill} onChange={e=>setMill(e.target.value)}>{r.mills.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><p>{tr("Product:")} {tr(r.products.find(p=>p.id===haulProduct)?.name??'Choose a product')} {tr("· change the product filter above.")}</p><label>{tr("Loads")}<input type="number" min="1" max="1000" value={loads} onChange={e=>setLoads(Number(e.target.value))}/></label><p>{access?tr("Forecast road connection available."):tr("No forecast-accessible connection or resource unavailable.")} {tr("Load fulfillment depends on available stock and time.")}</p>{restriction&&<p role="status">{restriction.reason==='fixed'?(language==='fr'?`L’accord ${restriction.pair} réserve ce bois aux livraisons ordinaires à ${restriction.ownMill} jusqu’au tour ${restriction.deadline}. Choisissez cette usine pour ajouter un transport.`:`Agreement ${restriction.pair} restricts this timber to ordinary deliveries at ${restriction.ownMill} through turn ${restriction.deadline}. Choose that mill to append a haul.`):(language==='fr'?`L’accord ${restriction.pair} protège le service à ${restriction.ownMill}. Une livraison à cette usine plus tôt dans le même tour peut libérer du stock; vérifiez la prévision après avoir ordonné les transports.`:`Agreement ${restriction.pair} protects service to ${restriction.ownMill}. An own-mill delivery earlier in the same turn can release stock; review the forecast after ordering the hauls.`)}</p>}<button disabled={fixedDestination||!access||!game.stands.find(s=>s.id===selected)?.owned||!vehicle?.hours||!destination||destination.prices[haulProduct]===undefined||!Number.isInteger(loads)||loads<1||loads>1000} onClick={()=>{const next=structuredClone(game);next.plan.trucks[truck].push({stand:selected,mill,product:haulProduct,loads});next.plan.ready={purchase:false,production:false,transport:false};onChange(next);setNotice('Haul appended. Review forecast fulfillment below.');}}>{tr("Append haul")}</button></fieldset>}
 {notice&&<p role="status">{tr(notice)}</p>}
 {done?<details open><summary>{tr("Completed campaign totals · all zones")}</summary><p>{tr("Recorded harvest and deliveries across all completed turns. Roadside stock is the remaining inventory; no further dispatch is possible in this campaign.")}</p>{r.products.filter(p=>!product||p.id===product).map(p=><article className="workbench-balance" key={p.id}><ProductSymbol product={p}/><dl><dt>{tr("Harvested")}</dt><dd>{f(game.history.reduce((n,h)=>n+(h.harvested[p.id]??0),0))} m³</dd><dt>{tr("Delivered")}</dt><dd>{f(game.history.reduce((n,h)=>n+(h.delivered[p.id]??0),0))} m³</dd><dt>{tr("Roadside now")}</dt><dd>{f(game.stands.reduce((n,s)=>n+(stockAt(game,s.id)[p.id]??0),0))} m³</dd></dl></article>)}</details>:<details open><summary>{tr("Targets and forecast · all zones")}</summary><p className="muted">{tr((r.turnDurationWeeks??1)===1?"Current period commitments and receipts; forecast is this week only. Zone filter applies to sites and weather, not mill totals.":"Current period commitments and receipts; forecast is this turn only. Zone filter applies to sites and weather, not mill totals.")}</p>{balance.filter(b=>!product||b.product.id===product).map(b=><article className="workbench-balance" key={b.product.id}><ProductSymbol product={b.product}/><dl><dt>{tr("Remaining commitment")}</dt><dd>{f(b.target)} m³</dd><dt>{tr("Roadside now")}</dt><dd>{f(b.roadside)} m³</dd><dt>{tr("Forecast production")}</dt><dd>{preview.report?f(preview.report.harvested[b.product.id]??0)+' m³':tr("Unavailable")}</dd><dt>{tr("Forecast delivery")}</dt><dd>{preview.report?f(preview.report.delivered[b.product.id]??0)+' m³':tr("Unavailable")}</dd><dt>{tr("Received this period")}</dt><dd>{f(r.mills.reduce((n,m)=>n+(game.deliveries[m.id]?.[b.product.id]??0),0))} m³</dd><dt>{tr("Remaining market demand")}</dt><dd>{f(b.demand)} m³</dd></dl></article>)}<p className="muted">{tr("Period")} {month(game)+1}{tr(". Forecast assumes forecast weather and excludes auction awards; it does not advance the game.")}</p>{(preview.report?.messages.length||preview.problems.length)>0&&<details><summary>{tr("Forecast constraints")}</summary>{(preview.report?.messages??preview.problems).map((m,i)=><p key={i}>{tr(m)}</p>)}</details>}</details>}
 </section>;
}
