import { useInteractiveTeachingLanguage } from './teaching-interactive-language';
const french: Record<string, string> = {
  'Company savings and group balance': 'Économies des entreprises et équilibre des groupes',
  'Review on negotiation board': 'Examiner sur le tableau de négociation',
  'Balance each group’s savings in the allocation lab.': 'Équilibrez les économies de chaque groupe dans le laboratoire de répartition.',
  'Value not applied. Enter a finite number.': 'Valeur non appliquée. Saisissez un nombre fini.',
  'Press Enter or leave the savings field to apply it. Escape restores its saved value. Negative draft savings prevent publication.': 'Appuyez sur Entrée ou quittez le champ des économies pour appliquer la valeur. Échap rétablit la valeur enregistrée. Des économies négatives dans le brouillon empêchent la publication.',
  'Review the current draft': 'Examiner le brouillon actuel',
  'Draft savings (kSEK)': 'Économies du brouillon (kSEK)',
  'Current draft allocation': 'Répartition actuelle du brouillon',
  'Manual share overrides': 'Économies modifiées manuellement',
  'Available / offered savings (kSEK)': 'Économies disponibles / proposées (kSEK)',
  'Ready to publish': 'Prêt à publier',
  'Fix the draft before publishing': 'Corriger le brouillon avant de publier',
  'Balance each group’s savings; edit the company savings below.': 'Équilibrez les économies de chaque groupe; modifiez les économies des entreprises ci-dessous.',
  'Use finite, nonnegative savings for every company.': 'Utilisez des économies finies et non négatives pour chaque entreprise.',
  'Use groups of one or two companies in round A.': 'Formez des groupes d’une ou deux entreprises au tour A.',
  'Allocation unavailable; choose another preset or review the group.': 'Répartition indisponible; choisissez un autre modèle ou examinez le groupe.',
  'Draft matches the latest proposal.': 'Le brouillon correspond à la dernière proposition.',
  'Changes from the latest proposal': 'Modifications depuis la dernière proposition',
  'Dataset changed': 'Jeu de données modifié',
  'Round changed': 'Tour modifié',
  'Changed companies': 'Entreprises modifiées',
  'Different teaching dataset': 'Jeu de données pédagogique différent',
  'The previous offer uses a different company cost table. Savings changes across these datasets are not shown as allocation improvements.': 'L’offre précédente utilise un autre tableau de coûts des entreprises. Les écarts entre ces jeux de données ne sont pas présentés comme des améliorations de la répartition.',
  'Recorded offer dataset': 'Jeu de données de l’offre enregistrée',
  'Prior recorded acceptances stay with that proposal; a new proposal starts without acceptances.': 'Les acceptations enregistrées restent liées à cette proposition; une nouvelle proposition commence sans acceptation.',
  'Potential economic alternatives do not predict company responses or prevent publication.': 'Les possibilités économiques ne prédisent pas les réponses des entreprises et n’empêchent pas la publication.',
  'Allocation evidence and charts': 'Données et graphiques de répartition',
  'How the allocation presets work': 'Fonctionnement des modèles de répartition',
  'Edit groups and savings first; review the draft on the negotiation board before publishing.': 'Modifiez d’abord les groupes et les économies; examinez le brouillon sur le tableau de négociation avant de publier.',
  'Teaching dataset': 'Jeu de données pédagogique',
  '4 companies': '4 entreprises',
  '5 companies': '5 entreprises',
  'Group': 'Groupe',
  'Equal savings': 'Économies égales',
  'Shapley marginal contribution': 'Contribution marginale de Shapley',
  'Equal profit method · optimized stable allocation': 'Méthode du profit égal · répartition stable optimisée',
  'Volume-weighted total cost': 'Coût total pondéré par le volume',
  'Proportional standalone cost': 'Coût individuel proportionnel',
  'Nucleolus · lexicographic excess minimization': 'Nucléole · minimisation lexicographique des excès',
};
export function useNegotiationLanguage() {
  const context = useInteractiveTeachingLanguage();
  return { ...context, t: (key: string) => context.language === 'fr' ? french[key] ?? context.t(key) : key };
}
