import { parseNetworkLabSave } from "./network-lab-save";
import { useLanguage } from "./i18n";
import { useEffect,useRef,useState } from 'react';
import type { Game } from './simulation/types';
import { regionalNetworkCase,validateNetworkCase,networkOffer,answerNetworkOffer } from './simulation/network-dispatch';
import type { NetworkCase,NetworkOffer,NetworkSolution } from './simulation/network-dispatch';
type Run={independent:NetworkSolution;pooled:NetworkSolution;network:NetworkCase;context:string};
type Saved={warning?:string;version:1;editor:string;run:Run|null;offer:NetworkOffer|null};
export default function NetworkDispatchLab({game}:{game:Game}){
 const {t: tr,language}=useLanguage();
 const key=`forest-network-lab-v1-${game.region.id}`;
 const initial=():Saved=>{let damaged=false;try{const raw=localStorage.getItem(key);if(raw){return parseNetworkLabSave(raw);}}catch{damaged=true;}let editor='';try{editor=JSON.stringify(regionalNetworkCase(game),null,2);}catch{}return {version:1,editor,run:null,offer:null,...(damaged?{warning:"Saved network results could not be restored. The original save is retained. Start a new regional case or import a case to replace it."}:{})};};
 const [state,setState]=useState<Saved>(initial),[error,setError]=useState(state.warning??''),[method,setMethod]=useState<'equal'|'proportional'>('proportional');
 useEffect(()=>{if(state.warning)return;try{localStorage.setItem(key,JSON.stringify(state));}catch{setError('The lab could not save in this browser. Export the case and results to keep a copy.');}},[state,key]);
 const download=(name:string,value:unknown)=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);};
 const worker=useRef<Worker|null>(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[companyCount,setCompanyCount]=useState(()=>{try{const n=JSON.parse(state.editor)?.companies?.length;if(Number.isInteger(n)&&n>=2&&n<=5&&n<=game.region.mills.length&&n<=game.region.trucks.length)return n;}catch{}return Math.min(3,game.region.mills.length,game.region.trucks.length);});
 useEffect(()=>()=>worker.current?.terminate(),[]);
 const cancel=()=>{worker.current?.terminate();worker.current=null;setBusy(false);setProgress('Solve cancelled. The previous result is retained; campaign unchanged.');};
 const solve=()=>{try{
  const network=JSON.parse(state.editor) as NetworkCase;validateNetworkCase(game,network);
  worker.current?.terminate();setError('');setBusy(true);setProgress('Solving independent company schedules…');
  const context=`${game.region.name}, ${game.weatherId}, forecast known at turn ${game.week}`;
  const w=new Worker(new URL('./network-dispatch.worker.ts',import.meta.url),{type:'module'});worker.current=w;
  const finish=()=>{w.terminate();if(worker.current===w){worker.current=null;setBusy(false);}};
  w.onmessage=e=>{if(worker.current!==w)return;const m=e.data;if(m.kind==='progress'){setProgress(m.message);return;}if(m.kind==='result'){setState(current=>({...current,run:{network,independent:m.independent,pooled:m.pooled,context},offer:null}));setProgress('Independent and pooled schedules completed.');}else {setError(m.message);setProgress('Solve failed; the previous result is retained.');}finish();};
  w.onerror=e=>{if(worker.current!==w)return;setError(e.message||tr("Network solver worker failed."));setProgress('Solve failed; the previous result is retained.');finish();};
  w.postMessage({game,network});
 }catch(e){worker.current?.terminate();worker.current=null;setBusy(false);setError(String(e instanceof Error?e.message:e));}};

 const run=state.run,offer=state.offer,fmt=(n:number)=>n.toLocaleString('en-CA',{maximumFractionDigits:2});
 return <section className="panel"><span className="eyebrow">{tr("COOPERATIVE NETWORK LAB")}</span><h2>{tr("Negotiate savings from scheduled freight")}</h2><p>{tr("Compare identical shipments, deadlines and fleet in independent companies and a shared dispatch pool. This separate lab uses the regional road graph and published weather; it does not move campaign cargo or spend campaign cash.")}</p>
 <p className="muted">{tr("Exact integer optimization within a bounded policy: up to five companies, five vehicles, ten indivisible shipments and three turns; at most two shipments per vehicle per turn. Vehicles keep their location between trips and turns and must return to their starting depot by the horizon end. Routing uses the engine’s fastest open paths. No speculative empty relocation, cargo splitting or unmodelled subcontractor capacity is assumed. Outside-service quotes are guaranteed exogenous alternatives. Results are optimal for these enumerated choices, not a global unconstrained forestry optimum.")}</p>
 <p>{tr("Physical weeks per scheduling turn:")} {new Intl.NumberFormat(language==='fr'?'fr-CA':'en-CA',{maximumFractionDigits:3}).format(game.region.turnDurationWeeks??1)}. {tr("The generated case uses the campaign’s scaled fleet hours and fixed costs.")}</p><details><summary>{tr("Author fleet, companies, cargo and deadlines")}</summary><p>{tr("IDs identify cargo ownership and truck ownership. Nodes must exist in this region. All times are campaign turn numbers. Fleet hours constrain combined travel and handling per turn. Cost is kilometres × costKm, fixedWeekly for each turn, plus outsideCost for any outsourced shipment. Prices use")}{" "}{game.region.currency}.</p><label htmlFor="network-case-editor">{tr("Network case JSON")}</label><textarea disabled={busy} id="network-case-editor" rows={17} style={{width:'100%',fontFamily:'monospace'}} value={state.editor} onChange={e=>setState({...state,editor:e.target.value})}/></details>
 <div className="button-row"><label>{tr("Teaching case size")} <select disabled={busy} value={companyCount} onChange={e=>setCompanyCount(Number(e.target.value))}>{[2,3,4,5].filter(n=>n<=game.region.mills.length&&n<=game.region.trucks.length).map(n=><option key={n} value={n}>{n}{" "}{tr("companies ·")}{" "}{n*2}{" "}{tr("shipments")}</option>)}</select></label><button disabled={busy} onClick={()=>{try{setState({version:1,editor:JSON.stringify(regionalNetworkCase(game,companyCount),null,2),run:null,offer:null});setError('');}catch(e){setError(String(e));}}}>{tr("New regional teaching case")}</button><button className="primary" disabled={busy||!!state.warning} onClick={solve}>{tr("Solve independent and pooled schedules")}</button><label>{tr("Import case")} <input disabled={busy} type="file" accept="application/json,.json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>100000)throw Error('Case is too large.');const n=JSON.parse(await file.text());validateNetworkCase(game,n);setState({version:1,editor:JSON.stringify(n,null,2),run:null,offer:null});setError('');}catch(err){setError(String(err));}e.target.value='';}}/></label><button onClick={()=>{try{download('forest-network-case.json',JSON.parse(state.editor));}catch{setError('Correct the case JSON before exporting.');}}}>{tr("Export case")}</button></div>
 {progress&&<p role="status">{tr(progress)}</p>}{busy&&<button onClick={cancel}>{tr("Cancel network solve")}</button>}
 {error&&<p role="alert">{tr(error)}</p>}
 {run&&<><p><strong>{tr("Solved: optimal within the stated bounded policy.")}</strong> {run.context.replace(/forecast known at (?:week|turn)/,tr("forecast known at turn"))}{tr(". The solver runs in a cancellable background worker; no result is displayed as optimal after a failure. Editing the case does not change this frozen result; solve again to replace it.")}</p><p className="muted">{language==='fr'&&run.network.note.startsWith("Authored ownership and ")?`${tr("Authored regional transfer example:")} ${run.network.cargo.length}. ${tr("Network teaching assumptions")}`:tr(run.network.note)}</p>
 <div className="metric-grid"><article><small>{tr("Independent cost")}</small><strong>{fmt(run.independent.cost)} {game.region.currency}</strong></article><article><small>{tr("Pooled cost")}</small><strong>{fmt(run.pooled.cost)} {game.region.currency}</strong></article><article><small>{tr("Measured savings")}</small><strong>{fmt(run.independent.cost-run.pooled.cost)} {game.region.currency}</strong></article></div>
 <div className="table-wrap"><table><caption>{tr("Frozen cargo manifest")}</caption><thead><tr><th>{tr("Shipment")}</th><th>{tr("Owner")}</th><th>{tr("Origin → destination")}</th><th>{tr("Volume")}</th><th>{tr("Window")}</th></tr></thead><tbody>{run.network.cargo.map(c=><tr key={c.id}><td>{c.id}</td><td>{c.company}</td><td>{c.from} → {c.to}</td><td>{fmt(c.volume)} m³</td><td>{tr("Turn")} {c.release}–{c.deadline}</td></tr>)}</tbody></table></div>
 {[run.independent,run.pooled].map(s=><details key={s.mode} open={s.mode==="pooled"}><summary>{tr(s.mode)}: {s.columns}{" "}{tr("nondominated itineraries · fixed cost")}{" "}{fmt(s.fixedCost)}{" "}{tr("· outsourced")}{" "}{s.outsourced.join(', ')||tr("none")}</summary><div className="table-wrap"><table><thead><tr><th>{tr("Vehicle / owner")}</th><th>{tr("Turn")}</th><th>{tr("Shipment")}</th><th>{tr("Start → finish")}</th><th>{tr("Empty km")}</th><th>{tr("Loaded km")}</th><th>{tr("Return km")}</th><th>{tr("Hours")}</th><th>{tr("Variable cost")}</th></tr></thead><tbody>{s.itineraries.flatMap(p=>p.legs.map((l,i)=><tr key={`${p.vehicle}-${i}`}><td>{p.vehicle} / {p.company}</td><td>{l.week}</td><td>{l.job??tr("Wait / return")}</td><td>{l.from} → {l.to}</td><td>{fmt(l.emptyKm)}</td><td>{fmt(l.loadedKm)}</td><td>{fmt(l.returnKm)}</td><td>{fmt(l.hours)}</td><td>{fmt(l.cost)}</td></tr>))}</tbody></table></div></details>)}
 <h3>{tr("Allocate measured savings")}</h3><p>{tr("Each company receives its independent cost minus its share of measured savings. The pooled costs are fully recovered. Acceptance is a shared-device teaching decision, separate from authenticated classroom company consent.")}</p><div className="button-row"><label>{tr("Allocation")} <select value={method} onChange={e=>setMethod(e.target.value as typeof method)}><option value="proportional">{tr("Proportional to independent cost")}</option><option value="equal">{tr("Equal savings")}</option></select></label><button onClick={()=>{try{setState({...state,offer:networkOffer(run.network,run.independent,run.pooled,method)});setError('');}catch(e){setError(String(e));}}}>{tr("Freeze proposal for this solution")}</button><button onClick={()=>download('forest-network-result.json',{version:1,run,offer})}>{tr("Export result and decisions")}</button></div>
 {offer&&<><p role="status">{tr("Offer:")}{" "}{tr(offer.status)}. {offer.accepted.length} / {run.network.companies.length}{" "}{tr("companies accepted.")}</p><div className="table-wrap"><table><thead><tr><th>{tr("Company")}</th><th>{tr("Independent cost")}</th><th>{tr("Allocated cost")}</th><th>{tr("Savings")}</th><th>{tr("Decision")}</th></tr></thead><tbody>{run.network.companies.map(c=><tr key={c.id}><td>{c.name}</td><td>{fmt(run.independent.companyCosts[c.id])}</td><td>{fmt(offer.costs[c.id])}</td><td>{fmt(offer.savings[c.id])}</td><td>{offer.accepted.includes(c.id)?tr("Accepted"):offer.rejected.includes(c.id)?tr("Rejected"):offer.status==="proposed"?<><button onClick={()=>setState({...state,offer:answerNetworkOffer(offer,c.id,true)})}>{tr("Accept for")}{" "}{c.id}</button><button onClick={()=>setState({...state,offer:answerNetworkOffer(offer,c.id,false)})}>{tr("Reject for")}{" "}{c.id}</button></>:tr("Closed")}</td></tr>)}</tbody></table></div></>}
 </>}
 </section>;
}
