import {effectiveMarketRegion} from "./simulation/bc-market";
import { useLanguage } from "./i18n";
import {useState} from 'react';
import type {Game,OfftakeOffer} from './simulation/types';
import {acceptOfftake,acceptAgreement} from './simulation/offtake';
import {stockAt} from './simulation/engine';
export default function OfftakeDesk({game,onChange,allowAccept=true,allowDispatch=true,onAccept,onAcceptAgreement}:{game:Game;onChange:(g:Game)=>void;allowAccept?:boolean;allowDispatch?:boolean;onAccept?:(id:string)=>void;onAcceptAgreement?:(id:string)=>void}) {
 const {t: tr}=useLanguage();
 const weekly=(game.region.turnDurationWeeks??1)===1;
 const [truck,setTruck]=useState(game.region.trucks[0].id),[selectedStand,setStand]=useState(''),[loads,setLoads]=useState(1),[error,setError]=useState('');
 const sources=game.region.stands.filter(s=>game.stands.find(t=>t.id===s.id)?.owned);
 const stand=sources.some(s=>s.id===selectedStand)?selectedStand:sources[0]?.id??'';
 const offers=game.region.offtakeOffers??[];
 const agreements=[...new Set(offers.flatMap(o=>o.agreement?[o.agreement]:[]))];
 const spots=effectiveMarketRegion(game).mills.flatMap(m=>Object.entries(m.spotPrices??{}).map(([product,price])=>({mill:m,product,price}))); 
 const renderOffer=(o:OfftakeOffer)=>{const state=game.offtake?.[o.id];return <article className="resource-card" key={o.id}><h3>{o.company}{o.agreement?` · ${tr("Deadline")} ${o.deadline}`:''}</h3><p>{o.volume.toLocaleString()} m³ {tr(game.region.products.find(p=>p.id===o.product)?.name??o.product)} → {game.region.mills.find(m=>m.id===o.mill)?.name??o.mill} {tr(weekly?"by week":"by turn")} {o.deadline}</p><p>{game.region.currency} {o.priceM3.toFixed(2)}{tr("/m³ · shortfall")} {o.shortfallM3}{tr(weekly?"/m³. Accept weeks":"/m³. Accept turns")} {o.opens}–{o.acceptBy}.</p><p>{tr("Selected source has")} {(stockAt(game,stand)[o.product]??0).toFixed(0)} {tr(weekly?"m³ roadside; this week’s production may add stock.":"m³ roadside; this turn’s production may add stock.")}</p>
 {state?<><strong>{state.delivered.toFixed(0)} / {o.volume} {tr("m³ delivered ·")} {tr(state.settled?'Settled':'Accepted')}</strong><button disabled={!stand||!allowDispatch||state.settled||game.week>o.deadline||state.delivered>=o.volume} onClick={()=>{
  if(!Number.isInteger(loads)||loads<1||loads>1000||!game.stands.find(s=>s.id===stand)?.owned){setError('Choose an owned stand and 1–1000 whole loads.');return;}
  const g=structuredClone(game);g.plan.trucks[truck].push({stand,mill:o.mill,product:o.product,loads,offtake:o.id});g.plan.ready={purchase:false,production:false,transport:false};onChange(g);setError('Contract order appended. Rehearse the plan to check stock, access and truck hours.');
 }}>{tr("Append contract delivery")}</button></>:o.agreement?<p>{tr("Accept this leg through its complete agreement above.")}</p>:<button disabled={!allowAccept||game.week<o.opens||game.week>o.acceptBy} onClick={()=>{try{if(onAccept){onAccept(o.id);return;}onChange(acceptOfftake(game,o.id));setError('Contract accepted; the volume and deadline are now binding.');}catch(e){setError(String(e));}}}>{tr("Accept binding offer")}</button>}
 </article>;};
 return <section className="panel"><h2>{tr("Partner timber contracts")}</h2><p>{tr("Accepted offtake creates a firm obligation for your timber. Deliveries consume stock and fleet time and earn the contract price, adjusted for quality. They are separate from ordinary mill demand and monthly commitments. Unfilled volume is charged once at the deadline.")}</p>
 {!offers.length&&<p>{tr("No partner offtake offers in this campaign. Enable teaching offers in Scenario studio before starting a new campaign, or import a region with authored offers.")}</p>}
 {(!!offers.length||!!spots.length)&&<><div className="form-grid"><label>{tr("Truck")}<select value={truck} onChange={e=>setTruck(e.target.value)}>{game.region.trucks.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>{tr("Source stand")}<select value={stand} onChange={e=>setStand(e.target.value)}>{sources.map(s=><option key={s.id} value={s.id}>{s.id} · {s.name}</option>)}</select></label><label>{tr("Loads")}<input type="number" min="1" max="1000" value={loads} onChange={e=>setLoads(Number(e.target.value))}/></label></div>
 {agreements.map(id=>{const legs=offers.filter(o=>o.agreement===id),accepted=legs.every(o=>game.offtake?.[o.id]);return <article className="soft-card" key={id}><h3>{tr("Repeated agreement ·")} {legs[0].company}</h3><p>{legs.length} {tr("dated obligations ·")} {legs.reduce((n,o)=>n+o.volume,0).toLocaleString()} {tr("m³ total. Each leg settles independently at its stated deadline. Accepting binds all legs together; unused volume does not roll between periods.")}</p><p>{tr("Maximum volume-shortfall charges:")} {game.region.currency} {legs.reduce((n,o)=>n+o.volume*o.shortfallM3,0).toLocaleString()}{tr(". Review every dated leg below before accepting.")}</p><button disabled={accepted||!allowAccept||legs.some(o=>game.offtake?.[o.id]||game.week<o.opens||game.week>o.acceptBy)} onClick={()=>{try{if(onAcceptAgreement){onAcceptAgreement(id);return;}if(onAccept){setError('Grouped acceptance is not supported by this classroom connection.');return;}onChange(acceptAgreement(game,id));setError('All agreement legs accepted together.');}catch(e){setError(String(e));}}}>{tr(accepted?'Agreement accepted':'Accept all agreement legs')}</button><details><summary>{tr("Review")} {legs.length} {tr("dated legs and dispatch deliveries")}</summary><div className="resource-grid">{legs.map(renderOffer)}</div></details></article>;})}
 <div className="resource-grid">{offers.filter(o=>!o.agreement).map(renderOffer)}</div>
 {!!spots.length&&<><h3>{tr("Spot outlets")}</h3><p>{tr("No demand ceiling; stock and transport still limit delivery. These sales do not satisfy partner contracts or monthly commitments.")}</p>{spots.map(s=><button key={`${s.mill.id}-${s.product}`} disabled={!stand||!allowDispatch||game.week>game.region.weeks} onClick={()=>{
  if(!Number.isInteger(loads)||loads<1||loads>1000||!game.stands.find(t=>t.id===stand)?.owned){setError('Choose an owned source and 1–1000 whole loads.');return;}
  const g=structuredClone(game);g.plan.trucks[truck].push({stand,mill:s.mill.id,product:s.product,loads,spot:true});g.plan.ready={purchase:false,production:false,transport:false};onChange(g);setError('Spot delivery appended to the truck queue.');
 }}>{tr("Ship")} {tr(game.region.products.find(p=>p.id===s.product)?.name??s.product)} {tr("to")} {s.mill.name} · {s.price.toFixed(2)}/m³</button>)}</>}
 </>}{error&&<p role="status">{tr(error)}</p>}</section>;
}
