import { useLanguage } from "./i18n";
import TimeSeries from "./charts/TimeSeries";
import WeatherCharts from "./WeatherCharts";
import ProductionCharts from "./ProductionCharts";
import {useMemo,useState} from 'react';
import type {Game} from './simulation/types';
import {cumulativeDeliveries,millPeriod,fleetUtilization,stockComposition} from './simulation/chart-data';
import {rollingForecast} from './simulation/harvest-planning';
import './charts.css';
const f=(n:number)=>Math.round(n).toLocaleString('en-CA');
const colors={thaw:'#c75246',wet:'#d28d35',normal:'#428269',frozen:'#436d96'};
export function WeatherMatrix({game}:{game:Game}){
 const {t:tr}=useLanguage();
 const r=game.region;
 return <section className="panel"><h2>{tr("Forecast and observed access conditions")}</h2><p>{tr("Each zone has a forecast row and a settled-weather row. Future observations remain hidden. These are access categories, not measured temperature, snow or precipitation.")}</p><div className="table-wrap"><table className="weather-matrix"><thead><tr><th>{tr("Zone / information")}</th>{Array.from({length:r.weeks},(_,i)=><th key={i}>{tr((r.turnDurationWeeks??1)!==1?'Turn':'Week').charAt(0)}{i+1}</th>)}</tr></thead><tbody>{r.zones.flatMap(z=>['forecast','observed'].map(kind=><tr key={z.id+kind}><th>{tr(z.name)} · {tr(kind)}</th>{Array.from({length:r.weeks},(_,i)=>{const w=kind==='forecast'?r.weather[game.weatherId].forecast[z.id][i]:game.history.find(h=>h.week===i+1)?.weather[z.id];return <td key={i} style={{background:w?colors[w]:'#eef1ea',color:w?'white':'#526457'}}>{w?tr(w):'—'}</td>})}</tr>))}</tbody></table></div></section>;
}
export default function OperationsCharts({game}:{game:Game}){
 const {t: tr}=useLanguage();
 const r=game.region,[mill,setMill]=useState('all'),[product,setProduct]=useState('all'),[period,setPeriod]=useState(Math.floor((Math.min(game.week,r.weeks)-1)/r.weeksPerMonth)),[forecast,setForecast]=useState(false);
 const rehearsal=useMemo(()=>forecast?rollingForecast(game,4):null,[game,forecast]),points=useMemo(()=>cumulativeDeliveries(game,mill,product,rehearsal?.reports),[game,mill,product,rehearsal]);
 const matrix=millPeriod(game,Math.min(period,Math.ceil(r.weeks/r.weeksPerMonth)-1)),stock=stockComposition(game),maxStock=Math.max(1,...stock.map(s=>s.standing+s.roadside)),latest=game.history.at(-1),fleet=latest?fleetUtilization(game,latest):[];
 return <><section className="panel"><h2>{tr("Cumulative deliveries against commitments")}</h2><div className="form-row"><label>{tr("Chart destination")}<select value={mill} onChange={e=>setMill(e.target.value)}><option value="all">{tr("All mills")}</option>{r.mills.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>{tr("Chart assortment")}<select value={product} onChange={e=>setProduct(e.target.value)}><option value="all">{tr("All assortments")}</option>{r.products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={forecast} onChange={e=>setForecast(e.target.checked)}/> {tr("Show four-week queue rehearsal")}</label></div><p>{tr("Cumulative volume resets each delivery period. The dashed line distributes each period's commitment evenly as a pace guide; settlement still happens at period end. Future-period targets use default demand until agreed.")}</p><TimeSeries title="Cumulative delivery commitments" unit="m³" series={[
 {name:'Actual delivered',color:'#17694e',values:points.map(p=>({x:p.week,y:p.actual,group:p.period}))},
 {name:'Commitment pace',color:'#6e786b',dashed:true,values:points.map(p=>({x:p.week,y:p.target,group:p.period}))},
 ...(forecast?[{name:'Forecast rehearsal',color:'#ab6819',dashed:true,values:points.map(p=>({x:p.week,y:p.forecast,group:p.period}))}]:[])
 ]}/>{rehearsal?.problem&&<p role="status">{rehearsal.problem}</p>}</section>
 <section className="panel"><h2>{tr("Mill and assortment fulfillment")}</h2><label>{tr("Delivery period")}<select value={period} onChange={e=>setPeriod(Number(e.target.value))}>{Array.from({length:Math.ceil(r.weeks/r.weeksPerMonth)},(_,i)=><option key={i} value={i}>{tr("Period")} {i+1}</option>)}</select></label><p>{tr("Delivered / commitment in m³. Green is within the")} {r.economy.tolerance*100}{tr("% tolerance; amber is below, purple above. Current-period cells show progress, not settled success.")}{matrix.assumed?' Targets for this future period are default assumptions.':''}</p><div className="table-wrap"><table className="fulfillment-matrix"><thead><tr><th>{tr("Mill")}</th>{r.products.map(p=><th key={p.id}>{p.name}</th>)}</tr></thead><tbody>{matrix.rows.map(row=><tr key={row.mill.id}><th>{row.mill.name}</th>{row.products.map(p=>{const status=!p.target?'no-target':p.delivered<p.target*(1-r.economy.tolerance)?'below':p.delivered>p.target*(1+r.economy.tolerance)?'above':'within';return <td key={p.product.id} className={status}>{f(p.delivered)} / {f(p.target)}<small>{p.target?`${f(p.delivered/p.target*100)}% · ${status}`:'No commitment'}</small></td>})}</tr>)}</tbody></table></div></section>
 <section className="panel"><h2>{tr("Secured supply and roadside stock")}</h2><p>{tr("Eligible standing timber after retention and current roadside inventory, by assortment. Standing volume still requires production capacity before it can be hauled.")}</p>{stock.map(s=><div className="chart-bar-row" key={s.product.id}><span>{s.product.name}</span><div className="chart-bar-track" aria-label={`${s.product.name}: ${f(s.standing)} standing, ${f(s.roadside)} roadside cubic metres`}><span style={{width:`${s.standing/maxStock*100}%`,background:'#397b57'}}/><span style={{width:`${s.roadside/maxStock*100}%`,background:'#c48b3b'}}/></div><small>{f(s.standing)} {tr("standing ·")} {f(s.roadside)} {tr("roadside")}</small></div>)}</section>
 <section className="panel"><h2>{tr("Fleet capacity")}{latest?` · week ${latest.week}`:''}</h2><p>{tr("Amber is travel or relocation; green is production or truck handling. Older saves without truck activity records show combined operating time.")}</p>{!latest?<p>{tr("Run a week to see actual utilization.")}</p>:fleet.map(c=><div className="chart-bar-row" key={c.id}><span>{c.name}</span><div className="chart-bar-track" aria-label={`${c.name}: ${c.used.toFixed(1)} of ${c.capacity} hours used`}><span style={{width:`${c.capacity?Math.min(100,(c.travel??0)/c.capacity*100):0}%`,background:'#c48b3b'}}/><span style={{width:`${c.capacity?Math.min(100,c.work/c.capacity*100):0}%`,background:'#397b57'}}/></div><small>{c.used.toFixed(1)} / {c.capacity} h{c.travel!==null?` · ${c.travel.toFixed(1)} h ${c.kind==='crew'?'relocating':'travelling'}`:''}</small></div>)}</section><ProductionCharts game={game}/><WeatherCharts game={game}/><WeatherMatrix game={game}/></>;
}
