import { useLanguage } from "./i18n";
import {useState} from 'react';
import {area,scaleLinear,stack} from 'd3';
import type {Game} from './simulation/types';
import TimeSeries from './charts/TimeSeries';
const f=(n:number)=>Math.round(n).toLocaleString('en-CA');
export function productionSeries(game:Game,product:string){
 return game.history.map(h=>{
  const row={week:h.week,public:0,forest:0,unknown:0};
  if(h.production)for(const p of h.production)row[p.roadClass]+=Object.entries(p.products).filter(([id])=>product==='all'||id===product).reduce((n,[,v])=>n+v,0);
  else row.unknown=Object.entries(h.harvested).filter(([id])=>product==='all'||id===product).reduce((n,[,v])=>n+v,0);
  return row;
 });
}
export default function ProductionCharts({game}:{game:Game}){
 const {t: tr}=useLanguage();
 const [product,setProduct]=useState('all'),[cumulative,setCumulative]=useState(true),[week,setWeek]=useState<number|null>(null);
 const rows=productionSeries(game,product);let totals={public:0,forest:0,unknown:0};
 const values=rows.map(r=>{if((r.week-1)%game.region.weeksPerMonth===0)totals={public:0,forest:0,unknown:0};for(const k of ['public','forest','unknown'] as const)totals[k]+=r[k];return cumulative?{week:r.week,...totals}:r;});
 const keys=['public','forest','unknown'] as const,colors={public:'#6798b0',forest:'#438161',unknown:'#b0a28a'},x=scaleLinear().domain([1,Math.max(2,game.region.weeks)]).range([62,720]),y=scaleLinear().domain([0,Math.max(1,...values.map(v=>v.public+v.forest+v.unknown))]).nice().range([230,25]);
 const periods=Array.from(new Set(values.map(v=>Math.floor((v.week-1)/game.region.weeksPerMonth))));
 return <section className="panel"><h2>{tr("Production by roadside access class")}</h2><div className="form-row"><label>{tr("Production assortment")}<select value={product} onChange={e=>setProduct(e.target.value)}><option value="all">{tr("All assortments")}</option>{game.region.products.map(p=><option key={p.id} value={p.id}>{tr(p.name)}</option>)}</select></label><label><input type="checkbox" checked={cumulative} onChange={e=>setCumulative(e.target.checked)}/> {tr("Cumulative within each delivery period")}</label></div><p>{tr("Actual harvested volume grouped by the stand's connecting road class. This is production at roadside, before dispatch; timber is not yet assigned to a mill. Forest access does not mean the entire onward route is forest road. Older saves without production records remain “unknown” instead of being reconstructed.")}</p>{!rows.length?<p>{tr("Run a week to record production provenance.")}</p>:<><div className="chart-scroll"><svg viewBox="0 0 760 280" role="img" aria-label={tr("Stacked actual production by roadside road class")}><title>{tr("Production by public, forest and unknown access")}</title>{y.ticks(5).map(v=><g key={v}><line x1="62" x2="720" y1={y(v)} y2={y(v)} stroke="#dce4d8"/><text x="55" y={y(v)+4} textAnchor="end">{f(v)}</text></g>)}{periods.map(period=>{const entries=values.filter(v=>Math.floor((v.week-1)/game.region.weeksPerMonth)===period);const layers=stack<(typeof values)[number]>().keys([...keys])(entries);return <g key={period}>{layers.map(layer=><g key={tr(layer.key)}><path d={area<(typeof layer)[number]>().x(d=>x(d.data.week)).y0(d=>y(d[0])).y1(d=>y(d[1]))(layer)??''} fill={colors[layer.key as keyof typeof colors]} opacity=".7"/>{layer.map(p=><circle key={p.data.week} cx={x(p.data.week)} cy={y(p[1])} r={3} fill={colors[layer.key as keyof typeof colors]} onMouseEnter={()=>setWeek(p.data.week)} onFocus={()=>setWeek(p.data.week)} tabIndex={0} aria-label={`${tr("Turn")} ${p.data.week}: ${tr(layer.key)} ${f(p[1]-p[0])} ${tr("cubic metres")}`}><title>{tr("Turn")} {p.data.week}: {tr(layer.key)} {f(p[1]-p[0])} m³</title></circle>)}</g>)}</g>})}{values.map(v=><text key={v.week} x={x(v.week)} y="256" textAnchor="middle">T{v.week}</text>)}</svg></div><p aria-live="polite">{week?`${tr("Turn")} ${week}: ${keys.map(k=>`${tr(k)} ${f(values.find(v=>v.week===week)?.[k]??0)} m³`).join(' · ')}`:tr('Select a point to inspect production volumes.')}</p><div className="d3-legend">{keys.map(k=><span key={tr(k)}><i style={{background:colors[k]}}/>{tr(k)}</span>)}</div><details><summary>{tr("Production road-class data")}</summary><div className="table-wrap"><table><thead><tr><th>{tr("Turn")}</th>{keys.map(k=><th key={tr(k)}>{tr(k)} m³</th>)}</tr></thead><tbody>{values.map(v=><tr key={v.week}><th>{v.week}</th>{keys.map(k=><td key={tr(k)}>{f(v[k])}</td>)}</tr>)}</tbody></table></div></details></>}
 <h3>{tr("Production and service are separate outcomes")}</h3><TimeSeries title={tr("Weekly harvest and deliveries")} unit="m³" series={[{name:'Harvested',color:'#438161',values:game.history.map(h=>({x:h.week,y:Object.entries(h.harvested).filter(([id])=>product==='all'||id===product).reduce((n,[,v])=>n+v,0)}))},{name:'Delivered',color:'#b47739',values:game.history.map(h=>({x:h.week,y:Object.entries(h.delivered).filter(([id])=>product==='all'||id===product).reduce((n,[,v])=>n+v,0)}))}]}/></section>;
}
