import ReciprocalSettlement from "./ReciprocalSettlement";
import ReciprocalService from './ReciprocalService';
import ReciprocalRenewal from './ReciprocalRenewal';
import {advancedMessage} from "./advanced-runtime";
import { useLanguage } from "./i18n";
import {useState} from 'react';
import type {Game} from './simulation/types';
import {acceptReciprocal,authorReciprocal,queueReciprocal,renewReciprocal,type ReciprocalPair} from './simulation/reciprocal';
import {forecastOutcome} from './simulation/planning';
export default function ReciprocalDesk({game,onChange}:{game:Game;onChange:(g:Game)=>void}){
 const {t: tr,language}=useLanguage();
 const quantity=(value:number,digits:number)=>value.toLocaleString(language==='fr'?'fr-CA':'en-CA',{minimumFractionDigits:digits,maximumFractionDigits:digits});
 const r=game.region,[a,setA]=useState(r.stands[0].id),[b,setB]=useState(r.stands[1]?.id??r.stands[0].id),[ma,setMa]=useState(r.mills[0].id),[mb,setMb]=useState(r.mills[1]?.id??r.mills[0].id),[product,setProduct]=useState(r.products[0].id),[limit,setLimit]=useState(500),[reserve,setReserve]=useState(50),[deadline,setDeadline]=useState(r.weeks),[error,setError]=useState(''),[preview,setPreview]=useState<string|{count:number;volume:number;savings:number;messages:string[]}>('');
 const [routing,setRouting]=useState<'fixed'|'flexible'>('flexible'),[minimumOwnA,setMinimumOwnA]=useState(0),[minimumOwnB,setMinimumOwnB]=useState(0);
 const [settlement,setSettlement]=useState<'paid'|'no-cash'>('paid');
 const matchingProducts=r.products.filter(p=>r.mills.find(m=>m.id===ma)?.prices[p.id]!==undefined&&r.mills.find(m=>m.id===mb)?.prices[p.id]!==undefined);
 const matchingProduct=matchingProducts.some(p=>p.id===product)?product:(matchingProducts[0]?.id??'');
 function act(fn:()=>Game){try{onChange(fn());setError('');setPreview('');}catch(e){setError(e instanceof Error?e.message:String(e));}}
 const select=(label:string,value:string,set:(s:string)=>void,rows:{id:string;name:string}[])=> <label>{tr(label)}<select value={value} onChange={e=>set(e.target.value)}>{rows.map(row=><option key={row.id} value={row.id}>{row.id} · {tr(row.name)}</option>)}</select></label>;
 return <section className="panel"><h2>{tr("Operational supply agreements")}</h2><p>{tr("This local managed-network exercise assigns two managed supplies to teaching companies A and B. Pass the device to each representative to accept frozen terms. These local confirmations are not authenticated outside-company contracts.")}</p><p>{tr("Fixed routing keeps covered timber at its own mill. Flexible routing permits balanced cross-deliveries after protecting outstanding own-mill requirements. Ordinary orders run first; both cross-delivery legs must fit the remaining stock, reservations, truck time and receiving demand.")}</p>
 <details><summary>{tr("Author a managed-network agreement")}</summary><fieldset disabled={game.week>r.weeks}><div className="form-row">{select('A supply',a,setA,r.stands)}{select('B supply',b,setB,r.stands)}{select('A mill',ma,setMa,r.mills)}{select('B mill',mb,setMb,r.mills)}{select('Matching product',matchingProduct,setProduct,matchingProducts)}<label>{tr("Campaign limit per leg (m³)")}<input type="number" min="1" value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label><label>{tr("Keep at each stand (m³)")}<input type="number" min="0" value={reserve} onChange={e=>setReserve(Number(e.target.value))}/></label></div><label>{tr("Routing rule")}<select value={routing} onChange={e=>setRouting(e.target.value as typeof routing)}><option value="flexible">{tr("Flexible routing")}</option><option value="fixed">{tr("Fixed own-mill routing")}</option></select></label><label>{tr("A own-mill minimum (m³)")}<input type="number" min="0" value={minimumOwnA} onChange={e=>setMinimumOwnA(Number(e.target.value))}/></label><label>{tr("B own-mill minimum (m³)")}<input type="number" min="0" value={minimumOwnB} onChange={e=>setMinimumOwnB(Number(e.target.value))}/></label><label>{tr("Settlement rule")}<select value={settlement} onChange={e=>setSettlement(e.target.value as typeof settlement)}><option value="paid">{tr("Paid savings sharing")}</option><option value="no-cash">{tr("No-cash exchange")}</option></select></label><label>{tr("Agreement closing turn")}<input type="number" min={game.week} max={r.weeks} value={deadline} onChange={e=>setDeadline(Number(e.target.value))}/></label><button disabled={!matchingProduct} onClick={()=>act(()=>authorReciprocal(game,{name:`${a} ↔ ${b}`,settlement,routing,minimumOwnA,minimumOwnB,standA:a,standB:b,millA:ma,millB:mb,product:matchingProduct,limitM3:limit,ownReserveM3:reserve,opens:game.week,deadline}))}>{tr("Create agreement")}</button></fieldset></details>
 {(r.reciprocalPairs??[]).map(pair=><ReciprocalAgreementCard key={pair.id} game={game} pair={pair} onChange={g=>act(()=>g)}/>)}{!r.reciprocalPairs?.length&&<p>{tr("No reciprocal agreements are authored. Select two supplies and compatible mills above to begin.")}</p>}
 <details><summary>{tr("Paired dispatch queue ·")}{" "}{game.plan.reciprocal?.length??0}</summary>{game.plan.reciprocal?.length?game.plan.reciprocal.map((order,i)=><p key={i}>{order.pair} · {order.truckA} / {order.truckB}{" "}{tr("· up to")}{" "}{order.loads}{" "}{tr("balanced loads")}{" "}<button disabled={game.week>r.weeks} onClick={()=>act(()=>{const next=structuredClone(game);next.plan.reciprocal!.splice(i,1);next.plan.ready={purchase:false,production:false,transport:false};return next;})}>{tr("Remove pair order")}</button></p>):<p>{tr("No paired dispatch queued.")}</p>}</details>
 <button disabled={game.week>r.weeks} onClick={()=>{try{const result=forecastOutcome(game);setPreview(result.report?{count:result.report.reciprocal?.length??0,volume:(result.report.reciprocal??[]).reduce((n,e)=>n+e.volumeEach,0),savings:(result.report.reciprocal??[]).reduce((n,e)=>n+e.savings,0),messages:result.report.messages.filter(m=>m.includes('paired')||m.includes('balanced'))}:result.problems.map(m=>advancedMessage(m,tr)).join(' '));}catch(e){setError(String(e));}}}>{tr("Rehearse remaining paired capacity")}</button>{preview&&<p role="status">{typeof preview==='string'?advancedMessage(preview,tr):<>{preview.count} {tr("balanced pairs forecast.")} {quantity(preview.volume,1)} {tr("m³ per side; combined transport cost difference")} {quantity(preview.savings,2)} {r.currency}. {preview.messages.map(m=>advancedMessage(m,tr)).join(' ')}</>}</p>}<p>{tr("“Savings” compares the two actual cross-delivery travel costs against direct delivery to each company’s own mill from the same opening truck positions. It can be negative, and does not certify baseline schedule feasibility. Transfers between A and B distribute this difference internally and do not add cash to the managed network. Timber sales and actual hauling costs are posted once to the campaign ledger.")}</p>{error&&<p role="alert">{tr(error)}</p>}</section>;
}
function ReciprocalAgreementCard({game,pair,onChange}:{game:Game;pair:ReciprocalPair;onChange:(g:Game)=>void}){
 const {t: tr,language}=useLanguage();
 const quantity=(value:number,digits:number)=>value.toLocaleString(language==='fr'?'fr-CA':'en-CA',{minimumFractionDigits:digits,maximumFractionDigits:digits});
 const saved=game.reciprocal?.[pair.id],[method,setMethod]=useState<'equal'|'cost-weighted'>(saved?.method??'equal'),[truckA,setA]=useState(game.region.trucks[0].id),[truckB,setB]=useState(game.region.trucks[1]?.id??game.region.trucks[0].id),[loads,setLoads]=useState(1),[error,setError]=useState('');
 const expired=game.week<pair.opens||game.week>pair.deadline||game.week>game.region.weeks;
 function act(fn:()=>Game){try{onChange(fn());setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}}
 return <article className="soft-card"><h3>{pair.name} · {pair.id}</h3>{pair.renews&&<p>{tr("Renewal of")} {pair.renews}</p>}<p>{pair.standA} → {pair.routing==='fixed'?pair.millA:pair.millB}; {pair.standB} → {pair.routing==='fixed'?pair.millB:pair.millA} · {pair.product}{tr(". Limit")}{" "}{pair.limitM3}{" "}{tr("m³ per side, reserve")}{" "}{pair.ownReserveM3}{" "}{tr("m³ at each stand. Active turns")}{" "}{pair.opens}–{pair.deadline}.</p><ReciprocalService game={game} pair={pair}/><p>{tr(pair.settlement==='no-cash'?"No-cash exchange: each company retains its own transport saving or loss; no balancing transfer is made.":"Paid savings sharing")}</p>{pair.settlement!=='no-cash'&&<label>{tr("Frozen savings/loss sharing")}<select disabled={!!saved||expired} value={saved?.method??method} onChange={e=>setMethod(e.target.value as typeof method)}><option value="equal">{tr("Equal")}</option><option value="cost-weighted">{tr("Proportional to direct transport cost")}</option></select></label>}<div className="button-row">{(['A','B'] as const).map(company=><button key={company} disabled={expired||saved?.accepted.includes(company)} onClick={()=>act(()=>acceptReciprocal(game,pair.id,company,saved?.method??method))}>{saved?.accepted.includes(company)?`${company} ${tr("accepted")}`:`${tr("Company")} ${company}: ${tr("accept terms")}`}</button>)}</div><p>{tr("Moved")}{" "}{saved?.movedM3??0}{" "}{tr("m³ each way. Recorded savings")}{" "}{quantity(saved?.savings??0,2)}{tr("; A share")}{" "}{quantity(saved?.shareA??0,2)}{tr("; B share")}{" "}{quantity(saved?.shareB??0,2)}{tr("; internal transfer to A")}{" "}{quantity(saved?.transferToA??0,2)} {game.region.currency}{tr(". A negative transfer is owed to B.")}</p><>{saved&&saved.movedM3>0&&<ReciprocalSettlement agreement={saved} currency={game.region.currency}/>}</><fieldset disabled={expired||saved?.accepted.length!==2||pair.routing==='fixed'}><legend>{tr("Append balanced load pairs")}</legend>{([['A',truckA,setA],['B',truckB,setB]] as const).map(([label,value,set])=><label key={tr(label)}>{tr("Truck")} {tr(label)}<select value={value} onChange={e=>set(e.target.value)}>{game.region.trucks.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label>)}<label>{tr("Load pairs")}<input type="number" min="1" max="100" value={loads} onChange={e=>setLoads(Number(e.target.value))}/></label><button onClick={()=>act(()=>queueReciprocal(game,pair.id,truckA,truckB,loads))}>{tr("Append paired dispatch")}</button></fieldset><ReciprocalRenewal game={game} pair={pair} onRenew={(opens,deadline)=>act(()=>renewReciprocal(game,pair.id,{opens,deadline}))}/>{expired&&<p>{tr("Agreement is outside its active window.")}</p>}{error&&<p role="alert">{tr(error)}</p>}</article>;
}
