import { useLanguage } from "./i18n";
import {bcEvidence} from './simulation/bc-evidence';
import { useEffect,useState } from 'react';
import type { RegionDefinition } from './simulation/types';
import { calibrationInputs,emptyCalibration,auditCalibration,validateCalibration,compareCalibration,recordCalibrationReview } from './simulation/regional-calibration';
import type { CalibrationManifest,CalibrationEntry,CalibrationStatus } from './simulation/regional-calibration';
export default function RegionalCalibration({region,onChange}:{region:RegionDefinition;onChange:(region:RegionDefinition)=>void}){
 const {t: tr}=useLanguage();
 const [draft,setDraft]=useState<CalibrationManifest>(()=>structuredClone(region.calibration??emptyCalibration(region))),[selected,setSelected]=useState(calibrationInputs[0].id),[error,setError]=useState(''),[notice,setNotice]=useState(''),[comparison,setComparison]=useState<ReturnType<typeof compareCalibration>>([]);
 useEffect(()=>{setDraft(structuredClone(region.calibration??emptyCalibration(region)));setComparison([]);},[region.id,region.calibration]);
 const audits=auditCalibration(region,draft),current=audits.find(d=>d.id===selected)!,entry=draft.entries[selected]??emptyCalibration(region).entries[selected];
 const update=(key:keyof CalibrationEntry,value:string)=>{setDraft({...draft,entries:{...draft.entries,[selected]:{...entry,[key]:value,...(key==='status'&&value!=='reviewed'?{reviewedFingerprint:''}:{})}}});setNotice('Unsaved evidence changes.');};
 const download=()=>{try{validateCalibration(draft);const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(draft,null,2)],{type:'application/json'}));a.href=url;a.download=`${region.id}-calibration.json`;a.click();URL.revokeObjectURL(url);setError('');}catch(e){setError(String(e));}};
 return <section className="panel"><span className="eyebrow">{tr("REGIONAL EVIDENCE AND REVIEW")}</span><h2>{tr("Track what supports each regional input")}</h2><p>{audits.filter(a=>a.reviewed).length} / {audits.length} {tr("input groups have recorded reviews matching current values. This is an evidence worksheet; recorded reviewer statements do not certify regional suitability or operational authority.")}</p><p className="muted">{tr("A British Columbia adaptation needs selected local datasets, applicable tenure and access rules, product definitions, and reviewed yield, ecology and cost parameters. Source links alone do not calibrate the game. No BC numeric preset is created here.")}</p>
 <details><summary>{tr("BC source findings and applicability")}</summary>{bcEvidence.map(source=><article key={source.url}><h3><a href={source.url} target="_blank" rel="noreferrer">{tr(source.title)}</a></h3><p>{tr(source.scope)} · {tr("Checked")} {source.checked}</p><p>{tr(source.finding)}</p><p className="muted">{tr(source.limit)}</p></article>)}</details>
 <label>{tr("Review target")} <input value={draft.targetRegion} onChange={e=>setDraft({...draft,targetRegion:e.target.value})}/></label>
 <div className="button-row"><button onClick={()=>{const next=emptyCalibration(region,true);setComparison(compareCalibration(draft,next));setDraft(next);setNotice('BC starting links added to the draft; all local values remain unreviewed. Save to include this worksheet in the region.');}}>{tr("Start BC evidence worksheet")}</button><button onClick={()=>{try{validateCalibration(draft);onChange({...region,calibration:structuredClone(draft)});setError('');setNotice('Evidence manifest saved in the region. Region JSON export includes it.');}catch(e){setError(String(e));}}}>{tr("Save evidence in region")}</button><button onClick={download}>{tr("Export evidence JSON")}</button><label>{tr("Import evidence JSON")} <input type="file" accept="application/json,.json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>250000)throw Error('Evidence file is too large.');const next=JSON.parse(await file.text());validateCalibration(next);if(!next)throw Error('Missing evidence manifest.');setComparison(compareCalibration(draft,next));setDraft(next);setError('');setNotice('Imported into draft. Compare changes and save to include in the region.');}catch(err){setError(String(err));}e.target.value='';}}/></label></div>
 {notice&&<p role="status">{tr(notice)}</p>}{error&&<p role="alert">{tr(error)}</p>}
 <div className="table-wrap"><table><caption>{tr("Current evidence coverage and changes since review")}</caption><thead><tr><th>{tr("Group")}</th><th>{tr("Input")}</th><th>{tr("Recorded status")}</th><th>{tr("Current audit")}</th><th>{tr("Missing evidence")}</th></tr></thead><tbody>{audits.map(a=><tr key={a.id}><td>{tr(a.group)}</td><th scope="row"><button aria-pressed={selected===a.id} onClick={()=>setSelected(a.id)}>{tr(a.title)}</button></th><td>{tr(a.entry?.status??'unknown')}</td><td>{tr(a.stale?'Values changed since review':a.reviewed?'Review matches current values':'Unreviewed / incomplete')}</td><td>{a.missing.length?a.missing.join(', '):tr('None')}</td></tr>)}</tbody></table></div>
 <h3>{tr(current.title)}</h3><p className="muted">{tr("Expected model units:")} {current.units}{tr(". Each group covers the corresponding values for all stands, mills or resources; specify the exact datasets, editions and parameter decisions in notes.")}</p>
 <div className="resource-grid">
 {(['sourceUrl','license','sourceDate','units','reviewer'] as const).map(k=><label key={k}>{tr(({sourceUrl:'Source URL',license:'Licence / use terms',sourceDate:'Source edition or evidence date',units:'Source/model units and conversion',reviewer:'Reviewer name / role'})[k])}<input type={k==='sourceDate'?'date':k==='sourceUrl'?'url':'text'} value={entry[k]} onChange={e=>update(k,e.target.value)}/></label>)}
 <label>{tr("Review status")} <select value={entry.status} onChange={e=>update('status',e.target.value as CalibrationStatus)}><option value="unknown">{tr("Unknown")}</option><option value="source-identified">{tr("Source identified")}</option><option value="review-needed">{tr("Needs review")}</option><option value="rejected">{tr("Rejected / unsuitable")}</option>{entry.status==='reviewed'&&<option value="reviewed">{tr("Reviewed current snapshot")}</option>}</select></label></div>
 <label>{tr("Applicability, exact source records, assumptions and limitations")}<textarea rows={5} style={{width:'100%'}} value={entry.notes} onChange={e=>update('notes',e.target.value)}/></label>
 <div className="button-row">{entry.sourceUrl&&/^https?:\/\//.test(entry.sourceUrl)&&<a href={entry.sourceUrl} target="_blank" rel="noreferrer">{tr("Open source reference")}</a>}<button onClick={()=>{try{setDraft(recordCalibrationReview(region,{...draft,entries:{...draft.entries,[selected]:entry}},selected));setError('');setNotice('Reviewer statement recorded for the current values. Save evidence to retain it in this region.');}catch(e){setError(String(e));}}}>{tr("Record review of current values")}</button></div>
 <p className="muted">{tr("This action records your review statement and a change-detection fingerprint. Changing any covered regional values makes the review stale. The app does not independently verify professional credentials, licensing rights, ecological validity or legal applicability.")}</p>
 {comparison.length>0&&<details open><summary>{tr("Imported/replaced evidence comparison")} ({comparison.length} {tr("changed groups")})</summary><ul>{comparison.map(c=><li key={c.id}>{tr(c.title)}: {tr(c.before)} → {tr(c.after)}; {tr("metadata changed.")}</li>)}</ul></details>}
 </section>;
}
