import {advancedMessage} from "./advanced-runtime";
import { useLanguage } from "./i18n";
import {reservationForecast} from './simulation/reservation-forecast';
import {useMemo,useState} from 'react';
import type {Game} from './simulation/types';
import {addReservation,type DestinationReservation} from './simulation/reservations';
export default function ReservationDesk({game,onChange,standId,completePlan=true}:{game:Game;onChange:(g:Game)=>void;standId?:string;completePlan?:boolean}) {
 const {t: tr,language}=useLanguage();
 const forecast=useMemo(()=>(game.plan.reservations?.length?reservationForecast(game,completePlan):{rows:[],problems:[]}),[game,completePlan]);
 const text=(en:string,fr:string)=>language==='fr'?fr:en;
 const number=(n:number|null)=>n===null?tr("Unavailable"):n.toLocaleString(language==='fr'?'fr-CA':'en-CA',{maximumFractionDigits:1});
 const [selected,setSelected]=useState(game.stands.find(s=>s.owned)?.id??''),[selectedProduct,setProduct]=useState(Object.keys(game.region.mills[0].prices)[0]??game.region.products[0].id),[selectedMill,setMill]=useState(game.region.mills[0].id),[volume,setVolume]=useState(40),[market,setMarket]=useState<DestinationReservation['market']>('ordinary'),[offer,setOffer]=useState(''),[error,setError]=useState('');
 const contracts=game.region.offtakeOffers?.filter(o=>game.offtake?.[o.id]&&!game.offtake[o.id].settled&&game.week<=o.deadline)??[];
 const contract=market==='offtake'?contracts.find(o=>o.id===offer):undefined;
 const mill=contract?.mill??(game.region.mills.some(m=>m.id===selectedMill)?selectedMill:game.region.mills[0].id);
 const destination=game.region.mills.find(m=>m.id===mill);
 const products=game.region.products.filter(p=>destination&&p.id in destination.prices&&(market!=='offtake'||p.id===contract?.product)&&(market!=='spot'||destination.spotPrices?.[p.id]!==undefined)&&(market!=='processing'||destination.processing?.inputs.includes(p.id)));
 const product=products.some(p=>p.id===selectedProduct)?selectedProduct:products[0]?.id??'';
 const requestedStand=standId??selected;
 const stand=standId!==undefined?(game.stands.some(s=>s.id===standId&&s.owned)?standId:''):(game.stands.some(s=>s.id===requestedStand&&s.owned)?requestedStand:game.stands.find(s=>s.owned)?.id??''),done=game.week>game.region.weeks,rows=game.plan.reservations??[];
 const mutate=(fn:(g:Game)=>void)=>{const g=structuredClone(game);fn(g);g.plan.ready={purchase:false,production:false,transport:false};onChange(g);};
 return <section className="panel reservation-desk"><h3>{tr("Destination reservations")}</h3><p>{tr("Reserve this stand’s assortment for a destination and market. Earlier reservations get available roadside stock first. Unproduced volume is a planning request, not a delivery guarantee; access, retention, mill demand and truck hours still apply.")}</p>
 <div className="form-grid">{!standId&&<label>{tr("Reservation stand")}<select value={stand} onChange={e=>setSelected(e.target.value)}>{game.stands.filter(s=>s.owned).map(s=><option key={s.id}>{s.id}</option>)}</select></label>}
 <label>{tr("Reservation product")}<select disabled={!products.length||market==='offtake'} value={product} onChange={e=>setProduct(e.target.value)}>{!products.length&&<option value="">{tr("No products for this market")}</option>}{products.map(p=><option key={p.id} value={p.id}>{tr(p.name)}</option>)}</select></label>
 <label>{tr("Reservation destination")}<select disabled={market==='offtake'} value={mill} onChange={e=>{setMill(e.target.value);const m=game.region.mills.find(m=>m.id===e.target.value)!;if(!(product in m.prices))setProduct(Object.keys(m.prices)[0]);}}>{game.region.mills.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>
 <label>{tr("Reservation market")}<select value={market} onChange={e=>setMarket(e.target.value as typeof market)}><option value="ordinary">{tr("Monthly mill commitment")}</option><option value="spot">{tr("Spot outlet")}</option><option value="processing">{tr("Mill processing intake")}</option><option value="offtake">{tr("Partner contract")}</option></select></label>
 {market==='offtake'&&<label>{tr("Accepted contract")}<select value={contract?.id??''} onChange={e=>{setOffer(e.target.value);const o=game.region.offtakeOffers?.find(o=>o.id===e.target.value);if(o){setProduct(o.product);setMill(o.mill);}}}><option value="">{tr("Choose contract")}</option>{contracts.map(o=><option key={o.id} value={o.id}>{o.company} · {tr("Deadline")} {o.deadline} · {o.id}</option>)}</select></label>}
 <label>{tr("Reserve m³")}<input type="number" min="0.01" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></label></div>
 <button disabled={done||!product||!stand||(market==='offtake'&&!contract)} onClick={()=>{try{onChange(addReservation(game,{stand,product,mill,volume,market,...(market==='offtake'?{offtake:offer}:{})}));setError('Destination reserved. Rehearse dispatch before running the week.');}catch(e){setError(String(e));}}}>{tr("Reserve destination")}</button>
 <ol>{rows.map((r,i)=><li key={r.id}>{r.stand} · {tr(game.region.products.find(p=>p.id===r.product)?.name??r.product)} → {game.region.mills.find(m=>m.id===r.mill)?.name??r.mill} · {tr({ordinary:"Monthly mill commitment",spot:"Spot outlet",processing:"Mill processing intake",offtake:"Partner contract"}[r.market])} · {r.volume.toFixed(1)} m³ <button aria-label={`${tr("Earlier")} · ${r.id} · ${r.stand} → ${r.mill}`} disabled={done||i===0} onClick={()=>mutate(g=>{const a=g.plan.reservations!;[a[i-1],a[i]]=[a[i],a[i-1]];})}>{tr("Earlier")}</button><button aria-label={`${text("Release reservation","Libérer la réservation")} · ${r.id} · ${r.stand} → ${r.mill}`} disabled={done} onClick={()=>mutate(g=>{g.plan.reservations=g.plan.reservations!.filter(v=>v.id!==r.id);})}>{text("Release reservation","Libérer la réservation")} {r.id}</button></li>)}</ol>
 {completePlan&&<p>{text('Forecast fulfillment follows all current crew and truck queues, with reservations competing for the same stock. Targets are shared by destination and product; do not add repeated target values. Processing and spot reservations do not cover ordinary targets.','La réalisation prévue suit toutes les files actuelles; les réservations se partagent le même stock. Les cibles sont communes par destination et produit : ne cumulez pas les valeurs répétées. La transformation et le comptant ne couvrent pas les cibles ordinaires.')}</p>}
 {!completePlan&&<p role="status">{text('Fulfillment forecast unavailable: other roles’ queues are private. Submit reservations and coordinate with transport; settled results show actual deliveries.','Prévision de réalisation indisponible : les files des autres rôles sont privées. Soumettez les réservations et coordonnez-vous avec le transport; les résultats réalisés indiquent les livraisons réelles.')}</p>}
 {forecast.problems.length>0&&<div role="status"><p>{text('Reservation forecast unavailable. Review these planning constraints:','Prévision des réservations indisponible. Examinez ces contraintes :')}</p><ul>{forecast.problems.map((problem,i)=><li key={i}>{advancedMessage(problem,tr)}</li>)}</ul></div>}
 <div className="table-wrap" tabIndex={0} role="region" aria-label={text('Reservation forecast table','Tableau des réservations prévues')}><table><caption>{text('Reservation coverage · current turn · m³','Couverture des réservations · tour actuel · m³')}</caption><thead><tr>{[tr('Destination'),tr('Product'),tr('Reservation market'),text('Requested','Demandé'),text('Forecast fulfilled','Réalisation prévue'),text('Still unfulfilled','Non réalisé'),text('Remaining target / contract','Cible / contrat restant')].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{forecast.rows.map(row=><tr key={row.id}><th>{row.stand} → {row.mill} · {row.id}</th><td>{tr(game.region.products.find(p=>p.id===row.product)?.name??row.product)}</td><td>{tr({ordinary:'Monthly mill commitment',spot:'Spot outlet',processing:'Mill processing intake',offtake:'Partner contract'}[row.market])}{row.offtake?` · ${row.offtake}`:''}</td><td>{number(row.volume)}</td><td>{number(row.fulfilled)}</td><td>{number(row.outstanding)}</td><td>{row.target===null?'—':number(row.target)}</td></tr>)}</tbody></table></div>
 {!rows.length&&<p>{text('No destination reservations yet.','Aucune réservation de destination.')}</p>}
 {error&&<p role="status">{tr(error)}</p>}</section>;
}
