import { useLanguage } from "./i18n";
import {useState} from 'react';
import type {Game} from './simulation/types';
import {beginLinkedSeason,illustrativeCalendar,seasonWindow,settleLinkedSeason} from './simulation/season-calendar';
export default function SeasonBuilder({game,onChange}:{game:Game;onChange:(g:Game)=>void}){
 const {t: tr}=useLanguage();
 const [start,setStart]=useState(13),[error,setError]=useState('');
 const base=game.linkedSeason?.baseRegion??game.region;
 const active=game.linkedSeason&&!game.linkedSeason.settled;
 const run=(fn:()=>Game)=>{try{onChange(fn());setError('');}catch(e){setError(String(e));}};
 if((base.turnDurationWeeks??1)!==1)return <section className="panel"><h2>{tr("Annual operating-window linkage unavailable")}</h2><p>{tr("Subweekly campaigns use a different operating clock. Start a weekly scenario to connect the authored annual calendar.")}</p></section>;
 if(!base.seasonCalendar)return <section className="panel"><h2>{tr("Season calendar")}</h2><p>{tr("This region has no authored 52-week access calendar. Regional calibration must be supplied before using it as a local forecast.")}</p>{base.id==='quebec-lac-saint-jean'&&<button onClick={()=>run(()=>({...game,region:{...game.region,seasonCalendar:illustrativeCalendar(base)}}))}>{tr("Add labelled Québec teaching calendar")}</button>}</section>;
 const preview=seasonWindow(base,start);
 return <section className="panel"><h2>{tr("Connected annual operating seasons")}</h2><p className="notice">{tr(base.seasonCalendar.provenance)}</p><p>{tr("Each annual turn contains one 12-week operating window followed by one annual growth step. The next window begins in the next management year, even if calendar week numbers wrap. Standing timber, secured rights, road improvements and cash carry forward. Unshipped roadside timber is written off during the long off-season and reported; no extra cash charge beyond settled operating costs. Annual harvest cooldowns temporarily close secured stands without selling their rights.")}</p><label>{tr("First calendar week")}{" "}<input aria-label={tr("Operating season start calendar week")} type="number" min={1} max={52} value={start} onChange={e=>setStart(Math.max(1,Math.min(52,Math.trunc(Number(e.target.value))||1)))}/></label><p>{tr("Opening source:")}{" "}{game.stewardship ? `${tr("annual year")} ${game.stewardship.year}, ${tr("budget")} ${game.region.currency} ${Math.round(game.stewardship.cash).toLocaleString()}` : `${tr("current operating forest, budget")} ${game.region.currency} ${Math.round(game.cash).toLocaleString()}`}{" "}{tr(". Existing independent annual state becomes the authoritative forest and budget; it is not combined with a divergent campaign.")}</p><p>{tr("Review: weeks")}{" "}{start}–{(start+10)%52+1}{" "}{tr("; three four-week delivery periods.")}{" "}{preview.disruptions?.length??0}{" "}{tr("dated disruptions overlap. Auctions and partner contracts use relative campaign weeks; they restart as fresh teaching offers each management year.")}</p><details><summary>{tr("Review forecast access and demand")}</summary>{preview.zones.map(z=><p key={z.id}>{tr(z.name)}: {preview.weather[game.weatherId].forecast[z.id].map(tr).join(' → ')}</p>)}{preview.mills.map(m=><p key={m.id}>{m.name}: {m.demand.map(d=>Math.round(Object.values(d).reduce((n,v)=>n+v,0)).toLocaleString()).join(' / ')}{" "}{tr("m³ per settlement period.")}</p>)}</details>{active?<><p>{tr("Active management year")}{" "}{game.linkedSeason!.opening.year}{" "}{tr(": operating week")}{" "}{Math.min(game.week,12)}{" "}{tr("of 12.")}</p><button disabled={game.week<=12} onClick={()=>run(()=>settleLinkedSeason(game))}>{tr("Settle season and apply this year's growth once")}</button></>:<button onClick={()=>run(()=>beginLinkedSeason(game,start))}>{tr("Start next annual operating window with carried forest and cash")}</button>}{error&&<p role="alert">{tr(error)}</p>}</section>;
}
