import {companyExplanations,geographyExplanation} from './company-explanations';
export const companyExplanationsFr:Record<string,string>={
 '1':'La carte concentre les approvisionnements et les industries réceptrices à l’est. Son trajet moyen est le plus long des entreprises présentées. Comparez si les approvisionnements voisins peuvent raccourcir les livraisons. La distance seule ne détermine pas les économies négociées.',
 '2':'La carte couvre une vaste zone avec de nombreuses industries réceptrices. Cette entreprise a le plus grand volume mensuel et le coût individuel le plus élevé. Une forte contribution aux économies totales ne définit pas une répartition équitable unique.',
 '3':'La carte couvre une grande partie de l’ouest et du centre avec un réseau récepteur dispersé. Recherchez des complémentarités entre l’offre et la demande des entreprises. Utilisez le tableau des coalitions pour quantifier cette possibilité.',
 '4':'La carte présente des approvisionnements plus petits et dispersés, avec moins de sites récepteurs que les entreprises 2 et 3. Comparez l’option individuelle au coût attribué proposé avant d’accepter une coalition.',
 '5':'La carte concentre ses principaux approvisionnements plus au sud et présente moins de sites récepteurs. Son trajet moyen est le plus court de cet ensemble. Des trajets individuels courts peuvent limiter les économies de certaines paires, sans exclure les gains d’une coalition plus grande.',
};
export const geographyExplanationFr='La figure 1 représente les zones d’approvisionnement en vert et les industries réceptrices en rouge. Les images expliquent la complémentarité géographique. Elles ne fournissent pas un réseau de routage, des capacités de ponts ou des conditions routières en direct. Les coûts proviennent du tableau optimisé des coalitions fourni. Ces réseaux pédagogiques sont distincts des cartes jouables du Québec et de la Colombie-Britannique.';
export const teachingFrench:Record<string,string>={
 ...Object.fromEntries(Object.entries(companyExplanations).map(([c,text])=>[text,companyExplanationsFr[c]])),
 [geographyExplanation]:geographyExplanationFr,
 'Geography and printable teaching packets':'Géographie et documents pédagogiques à imprimer',
 'Packet contents':'Contenu du document','Participant role cards':'Fiches de rôle des participants','Round A and B worksheets':'Feuilles de travail des tours A et B','Debrief and recorded offers':'Bilan et offres enregistrées','Download printable':'Télécharger le document imprimable',
 'Open the downloaded HTML in a browser, then print or save as PDF. Role cards include the source maps. Worksheets use the selected dataset; the debrief includes recorded offers and their acceptance status.':'Ouvrez le fichier HTML téléchargé dans un navigateur, puis imprimez-le ou enregistrez-le en PDF. Les fiches de rôle comprennent les cartes sources. Les feuilles utilisent le jeu de données sélectionné. Le bilan présente les offres enregistrées et leur statut d’acceptation.',
 'Open this file in a browser and print or save as PDF. Each role or round begins on a new page.':'Ouvrez ce fichier dans un navigateur pour l’imprimer ou l’enregistrer en PDF. Chaque rôle ou tour commence sur une nouvelle page.',
 'Improve your own transport cost while finding an agreement every member can accept. You may belong to only one coalition in a round.':'Réduisez votre coût de transport en trouvant un accord acceptable pour chaque membre. Vous ne pouvez appartenir qu’à une seule coalition par tour.',
 'Individual volume rows sum to 795,190 m³, versus the printed 795,200 m³. Standalone costs sum to 38,680 kSEK and grand-coalition savings are 2,990 kSEK.':'Les volumes individuels totalisent 795 190 m³, contre 795 200 m³ dans le total imprimé. Les coûts individuels totalisent 38 680 kSEK et les économies de la grande coalition atteignent 2 990 kSEK.',
 'This packet uses the four-company variant, including its distinct company 1 and 2 volumes.':'Ce document utilise la variante à quatre entreprises, avec ses volumes distincts pour les entreprises 1 et 2.',
 'Figure 1 and Tables 1–2, supplied with this project. Amounts are kSEK (thousands of Swedish kronor), separate from campaign CAD.':'figure 1 et tableaux 1–2, fournis avec ce projet. Les montants sont en kSEK (milliers de couronnes suédoises), distincts des CAD de la campagne.',
 'Only pairs or single companies are allowed.':'Seules les paires et les entreprises seules sont autorisées.',
 'Any coalition size is allowed.':'Toute taille de coalition est autorisée.',
 'Each company belongs to exactly one group. Agree a complete partition, savings and acceptance from every company.':'Chaque entreprise appartient à un seul groupe. Convenez d’une répartition complète, des économies et de l’acceptation de chaque entreprise.',
 'Check: shares sum to each coalition’s savings. Does any company lose relative to operating alone? Can another subgroup improve on its proposed shares?':'Vérifiez que les parts totalisent les économies de chaque coalition. Une entreprise perd-elle par rapport à son option individuelle ? Un autre sous-groupe peut-il améliorer ses parts proposées ?',
 'This is a comparison benchmark, not an instruction to accept a particular allocation.':'Ce repère permet de comparer les résultats. Il n’impose pas l’acceptation d’une répartition particulière.',
 'Compare the total savings and each company’s share in rounds A and B.':'Comparez les économies totales et la part de chaque entreprise aux tours A et B.',
 'Explain how geographic overlap differs from company size or mean haul distance.':'Expliquez comment le chevauchement géographique se distingue de la taille des entreprises ou de la distance moyenne de transport.',
 'Which outside option affected your agreement? Identify a blocking subgroup, or demonstrate stability.':'Quelle option individuelle a influencé votre accord ? Identifiez un sous-groupe bloquant ou démontrez la stabilité.',
 'Compare equal, proportional, volume, Shapley, EPM and nucleolus allocations. Which fairness claim does each represent?':'Comparez les répartitions égale, proportionnelle, selon le volume, Shapley, EPM et nucléole. Quelle conception de l’équité chacune représente-t-elle ?',
 'What changed after discussion? Separate a proposed offer from unanimous acceptance.':'Qu’est-ce qui a changé après discussion ? Distinguez une offre proposée d’une acceptation unanime.',
 'No recorded offers in this dataset. Complete the worksheet by hand.':'Aucune offre enregistrée pour ce jeu de données. Remplissez la feuille à la main.',
 'Source-table allocations are separate from actual campaign freight payments. Use Reports to discuss achieved service, crew relocation and measured partner savings.':'Les répartitions des tableaux sources sont distinctes des paiements réels de transport de la campagne. Utilisez les rapports pour discuter du service atteint, des déplacements des équipes et des économies mesurées des partenaires.',
 'Recorded offers for this dataset':'Offres enregistrées pour ce jeu de données','Maximum available grand-coalition savings':'Économies maximales disponibles de la grande coalition','Negotiation debrief':'Bilan de négociation','Monthly volume m³':'Volume mensuel m³','Standalone cost kSEK':'Coût individuel kSEK','Mean haul km':'Trajet moyen km','Standalone SEK/m³':'Coût individuel SEK/m³','Decision record':'Décision','Outside option: operate alone at':'Option individuelle : fonctionner seul à','Proposed partners':'Partenaires proposés','My savings':'Mes économies','My allocated cost':'Mon coût attribué','Accept / reject':'Accepter / refuser','Reason and alternative coalition':'Motif et autre coalition possible','Notes / evidence':'Notes / preuves','Joint cost kSEK':'Coût conjoint kSEK','Savings kSEK':'Économies kSEK','Allocated cost kSEK':'Coût attribué kSEK','Total savings':'Économies totales','Sum of allocated costs':'Somme des coûts attribués','Company savings kSEK':'Économies par entreprise kSEK','Accepted companies':'Entreprises ayant accepté','Agreement':'Accord','Coalition':'Coalition','Status':'Statut','Offer':'Offre','None':'Aucune','proposed':'proposée','agreed':'acceptée','rejected':'refusée','superseded':'remplacée','You represent company':'Vous représentez l’entreprise','Source supply areas and receiving industries for company':'Zones d’approvisionnement et industries réceptrices de l’entreprise','role card':'fiche de rôle','-company negotiation':' entreprises · négociation','Participant':'Participant','Group':'Groupe','Round':'Tour','worksheet':'feuille de travail','companies':'entreprises','Company':'Entreprise','Adapted from':'Adapté de','-company':' entreprises','roles packet':'fiches de rôle','rounds packet':'feuilles des tours','debrief packet':'bilan',
};
/** Translate authored HTML text and image alt text only; leave numeric records and data URLs intact. */
export function frenchTeachingHtml(html:string):string{
 const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
 const entries=Object.entries(teachingFrench).sort(([a],[b])=>b.length-a.length);
 const text=(s:string)=>s.split(/(Collaboration_[45]companiesEN\.docx)/).map(part=>/^Collaboration_[45]companiesEN\.docx$/.test(part)?part:entries.reduce((value,[en,fr])=>value.split(escape(en)).join(escape(fr)),part)).join('');
 return html.replace('lang="en"','lang="fr"').split(/(<[^>]+>)/g).map(part=>part.startsWith('<')?part.replace(/alt="([^"]*)"/g,(_,alt)=>`alt="${text(alt)}"`):text(part)).join('');
}
