import {frenchTeachingHtml} from './teaching-french';
import {cost,savings} from './coalition';
import {companyProfiles} from './company-profiles';
import {companyExplanations,geographyExplanation} from './company-explanations';
import type {Negotiation} from './simulation/types';
export type TeachingPacketKind='roles'|'rounds'|'debrief';
const escape=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function teachingPacket(count:4|5,kind:TeachingPacketKind,negotiation?:Negotiation,images:Record<string,string>={},language:'en'|'fr'='en'):string{
 if(![4,5].includes(count)||!['roles','rounds','debrief'].includes(kind))throw Error('Choose a validated four- or five-company packet.');
 const num=(v:number)=>v.toLocaleString(language==='fr'?'fr-CA':'en-CA',{maximumFractionDigits:2});
 const members=Array.from({length:count},(_,i)=>String(i+1));
 const table=(heads:string[],rows:string[][])=>`<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th>${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${escape(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 const source=`<footer>Adapted from Collaboration_${count}companiesEN.docx, Figure 1 and Tables 1–2, supplied with this project. Amounts are kSEK (thousands of Swedish kronor), separate from campaign CAD. ${count===5?'Individual volume rows sum to 795,190 m³, versus the printed 795,200 m³. Standalone costs sum to 38,680 kSEK and grand-coalition savings are 2,990 kSEK.':'This packet uses the four-company variant, including its distinct company 1 and 2 volumes.'}</footer>`;
 const lines='<p class="write">Notes / evidence:</p><div class="lines"></div>';
 let body='';
 if(kind==='roles')body=members.map(c=>{
  const p=companyProfiles[count][c];const image=images[c];
  return `<section><h1>Company ${c} role card</h1><p>${count}-company negotiation · Participant: __________________ · Group: __________________</p><p>You represent company ${c}. Improve your own transport cost while finding an agreement every member can accept. You may belong to only one coalition in a round.</p>${table(['Monthly volume m³','Standalone cost kSEK','Mean haul km','Standalone SEK/m³'],[[num(p.volume),num(cost([c],count)),num(p.distance),num(cost([c],count)*1000/p.volume)]])}<p>${escape(companyExplanations[c])}</p>${image?.startsWith('data:image/')?`<img class="map" alt="Source supply areas and receiving industries for company ${c}" src="${escape(image)}">`:''}<p>${escape(geographyExplanation)}</p><h2>Decision record</h2><p>Outside option: operate alone at ${num(cost([c],count))} kSEK. Proposed partners: __________________</p><p>My savings: __________ kSEK. My allocated cost: __________ kSEK.</p><p>Accept / reject: __________ Reason and alternative coalition: __________________</p>${lines}${source}</section>`;
 }).join('');
 if(kind==='rounds')body=['A','B'].map(round=>{
  const subsets=Array.from({length:2**count-1},(_,i)=>members.filter((_,j)=>(i+1)&(1<<j))).filter(s=>s.length>1&&(round==='B'||s.length===2));
  return `<section><h1>Round ${round} worksheet</h1><p>${count} companies · Group: __________________ · Date: __________________</p><p>${round==='A'?'Only pairs or single companies are allowed.':'Any coalition size is allowed.'} Each company belongs to exactly one group. Agree a complete partition, savings and acceptance from every company.</p>${table(['Coalition','Joint cost kSEK','Savings kSEK'],subsets.map(s=>[s.join(' + '),num(cost(s,count)),num(savings(s,count))]))}<div class="agreement"><h2>Round ${round} · Agreement</h2>${table(['Company','Coalition','Savings kSEK','Allocated cost kSEK','Accept / reject'],members.map(c=>[c,'____________','____________','____________','____________']))}<p>Total savings: __________ kSEK. Sum of allocated costs: __________ kSEK.</p><p>Check: shares sum to each coalition’s savings. Does any company lose relative to operating alone? Can another subgroup improve on its proposed shares?</p>${lines}${source}</div></section>`;
 }).join('');
 if(kind==='debrief'){
 const offers=negotiation?.offers?.filter(o=>o.count===count)??[];
 body=`<section><h1>Negotiation debrief</h1><p>${count} companies · Group: __________________</p><p>Maximum available grand-coalition savings: ${num(savings(members,count))} kSEK. This is a comparison benchmark, not an instruction to accept a particular allocation.</p><ol><li>Compare the total savings and each company’s share in rounds A and B.</li><li>Explain how geographic overlap differs from company size or mean haul distance.</li><li>Which outside option affected your agreement? Identify a blocking subgroup, or demonstrate stability.</li><li>Compare equal, proportional, volume, Shapley, EPM and nucleolus allocations. Which fairness claim does each represent?</li><li>What changed after discussion? Separate a proposed offer from unanimous acceptance.</li></ol>${lines}<h2>Recorded offers for this dataset</h2>${offers.length?table(['Offer','Status','Coalition','Company savings kSEK','Accepted companies'],offers.map(o=>[String(o.id),o.status,[...new Set(o.groups.slice(0,count))].map(group=>members.filter((_,i)=>o.groups[i]===group).join(' + ')).join('; '),members.map(c=>`${c}: ${num(o.shares[c]??0)}`).join('; '),o.accepted.join(', ')||'None'])):'<p>No recorded offers in this dataset. Complete the worksheet by hand.</p>'}<p>Source-table allocations are separate from actual campaign freight payments. Use Reports to discuss achieved service, crew relocation and measured partner savings.</p>${source}</section>`;
 }
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Forest Commons ${count}-company ${kind} packet</title><style>body{font:15px system-ui,sans-serif;color:#183a30;margin:24px auto;max-width:900px;padding:0 20px}section{break-after:page}section:last-child{break-after:auto}h1{font-size:26px}h2{font-size:19px}.table-wrap{max-width:100%;overflow-x:auto}table{width:100%;border-collapse:collapse;margin:14px 0;font-size:13px}th,td{padding:7px;border:1px solid #aabbb4;text-align:left}tr{break-inside:avoid}.agreement{break-inside:avoid}h1,h2{break-after:avoid}thead{display:table-header-group}footer{font-size:11px;margin-top:20px;color:#465c53}.map{max-height:260px;max-width:100%;display:block;margin:12px auto}.lines{height:80px;background:repeating-linear-gradient(white,white 25px,#ccd5cf 26px)}li{margin:12px 0}@media print{.table-wrap{overflow:visible}body{margin:0;padding:0;font-size:12px}.no-print{display:none}h1{font-size:22px}table{font-size:11px}.packet-debrief table{table-layout:fixed}.packet-debrief th,.packet-debrief td{overflow-wrap:anywhere}th,td{padding:5px}@page{size:A4;margin:14mm}}</style></head><body class="packet-${kind}"><p class="no-print">Open this file in a browser and print or save as PDF. Each role or round begins on a new page.</p>${body}</body></html>`;
 return language==='fr'?frenchTeachingHtml(html):html;
}
