import { useLanguage } from './i18n';

const french: Record<string, string> = {
  'Negotiation board': 'Tableau de négociation',
  'Draft allocation': 'Répartition en brouillon',
  'Publish proposal': 'Publier une proposition',
  'Company responses': 'Réponses des entreprises',
  'Agreement': 'Accord',
  'No proposal yet. Review the draft allocation, then publish it for company responses.': 'Aucune proposition pour le moment. Examinez le brouillon, puis publiez-le pour recueillir les réponses des entreprises.',
  'Publish revised allocation': 'Publier la répartition révisée',
  'Selected proposal': 'Proposition sélectionnée',
  'Select a proposal': 'Sélectionner une proposition',
  'Open for responses': 'Ouverte aux réponses',
  'All companies accepted': 'Toutes les entreprises ont accepté',
  'Rejected · closed': 'Rejetée · fermée',
  'Replaced by a later proposal': 'Remplacée par une proposition ultérieure',
  'Recorded acceptances': 'Acceptations enregistrées',
  'Awaiting response': 'En attente de réponse',
  'No acceptance recorded': 'Aucune acceptation enregistrée',
  'Change from previous offer (kSEK)': 'Écart avec l’offre précédente (kSEK)',
  'First offer': 'Première offre',
  'Not in previous offer': 'Absente de l’offre précédente',
  'Acceptance applies to this exact allocation.': 'L’acceptation porte sur cette répartition exacte.',
  'This record does not identify who rejected the offer or why. A company without acceptance is not necessarily the rejecting company.': 'Ce dossier ne précise pas qui a rejeté l’offre ni pourquoi. Une entreprise sans acceptation n’est pas nécessairement celle qui a rejeté l’offre.',
  'A later proposal closed this offer; its recorded acceptances remain in history.': 'Une proposition ultérieure a fermé cette offre; ses acceptations enregistrées restent dans l’historique.',
  'Every company accepted this offer.': 'Chaque entreprise a accepté cette offre.',
  'No motive is recorded for a company decision.': 'Aucun motif n’est enregistré pour la décision d’une entreprise.',
  'Economic evidence for this frozen offer': 'Données économiques de cette offre figée',
  'Total offered savings': 'Économies totales proposées',
  'Potential blocking coalitions': 'Coalitions de blocage potentielles',
  'Company group': 'Groupe d’entreprises',
  'Additional attainable savings': 'Économies supplémentaires possibles',
  'No subgroup can earn more than its offered savings under the teaching cost table.': 'Aucun sous-groupe ne peut obtenir davantage que les économies proposées selon le tableau de coûts pédagogique.',
  'These comparisons use the teaching cost table, not recorded reasons for company decisions.': 'Ces comparaisons utilisent le tableau de coûts pédagogique, et non des motifs enregistrés pour les décisions des entreprises.',
  'Each revised proposal freezes a new allocation and closes any earlier open proposal. Edit the draft allocation before publishing a revision.': 'Chaque proposition révisée fige une nouvelle répartition et ferme toute proposition antérieure encore ouverte. Modifiez le brouillon avant de publier une révision.',
  'Recorded year explorer': 'Explorateur des années enregistrées',
  'Recorded management year': 'Année d’aménagement enregistrée',
  'Previous recorded year': 'Année enregistrée précédente',
  'Next recorded year': 'Année enregistrée suivante',
  'Latest recorded year': 'Dernière année enregistrée',
  'Year-end observations': 'Observations en fin d’année',
  'Closing budget': 'Budget de clôture',
  'Planted stands': 'Parcelles plantées',
  'Recorded treatments': 'Traitements enregistrés',
  'Standing forest': 'Forêt sur pied',
  'No planting action recorded': 'Aucune action de plantation enregistrée',
  'History records landscape totals and treatment choices. Historical stand volumes and stand habitat were not saved; the current stand table below shows the present forest.': 'L’historique conserve les totaux du paysage et les traitements choisis. Les volumes et habitats passés par parcelle n’ont pas été sauvegardés; le tableau des parcelles ci-dessous montre la forêt actuelle.',
  'This year includes a connected operating season. Treatment labels describe recorded management actions, not individual deliveries.': 'Cette année comprend une saison opérationnelle connectée. Les étiquettes de traitement décrivent les actions d’aménagement enregistrées, et non les livraisons individuelles.',
  'Year-end budget sums the opening budget and recorded cash movements through the selected year.': 'Le budget de clôture additionne le budget initial et les mouvements de trésorerie enregistrés jusqu’à l’année sélectionnée.',
  'Scrollable annual treatment calendar': 'Calendrier défilant des traitements annuels',
};

export function useInteractiveTeachingLanguage() {
  const context = useLanguage();
  return { ...context, t: (key: string) => context.language === 'fr' ? french[key] ?? context.t(key) : key };
}
