import { useLanguage } from "./i18n";
import {useState} from 'react';
import type {RegionDefinition} from './simulation/types';
import {subdividedScenario,turnDuration} from './simulation/turn-duration';
export default function TurnDurationMode({region,onChange}:{region:RegionDefinition;onChange:(r:RegionDefinition)=>void}){
 const {t: tr}=useLanguage();
 const [error,setError]=useState(''),[divisions,setDivisions]=useState<2|4|7>(2),duration=turnDuration(region),converted=duration!==1;
 return <section className="soft-card"><h3>{tr("Decision interval")}</h3><p>{region.weeks} {tr("turns over")} {(region.weeks*duration).toFixed(1)} {tr("physical weeks. Settlement periods contain")} {region.weeksPerMonth} {tr("turns.")}</p><p>{tr("Prepare a separate scenario with two, four or seven equal turns per week. Crew/truck availability, recurring costs and mill throughput scale with elapsed time. Opening dates, closing dates and freshness windows retain their physical meaning. Travel, handling, prices and settlement-period demand remain unchanged. More frequent decisions can change results.")}</p><p>{tr("Annual operating-window linkage and the 52-week chart calendar are unavailable for subweekly campaigns. Independent annual forest growth remains an annual teaching action.")}</p>{!converted&&<><label>{tr("Turns per week")}<select value={divisions} onChange={e=>setDivisions(Number(e.target.value) as 2|4|7)}><option value="2">{tr("2 · half-week")}</option><option value="4">{tr("4 · quarter-week")}</option><option value="7">{tr("7 · daily")}</option></select></label><button disabled={region.weeks*divisions>104} onClick={()=>{try{onChange(subdividedScenario(region,divisions));setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}}}>{tr("Prepare separate scenario")}</button>{region.weeks*divisions>104&&<p>{tr("This interval exceeds the 104-turn limit. Choose fewer turns or a shorter source scenario.")}</p>}</>}{converted&&<p role="status">{tr("Start a new campaign to use this scenario. Reload the original scenario to change its interval; an existing save is never reinterpreted.")}</p>}{error&&<p role="alert">{tr(error)}</p>}</section>;
}
