import {describe,it,expect,vi,afterEach} from 'vitest';
import {createGame,advance} from './engine';
import {quebec} from '../scenarios/quebec';
import {deliverability} from './deliverability';
import * as planning from './planning';
afterEach(()=>vi.restoreAllMocks());
function fixture(){const g=createGame(quebec),stand=g.region.stands.find(s=>g.stands.find(t=>t.id===s.id)!.owned)!;g.crewPositions=Object.fromEntries(g.region.crews.map(c=>[c.id,stand.node]));g.truckPositions=Object.fromEntries(g.region.trucks.map(t=>[t.id,stand.node]));for(const e of g.region.roads.edges)e.bearing=1;stand.terrain=1;return {g,stand};}
describe('capacity-aware supply screening',()=>{
 it('shows actual hours remaining after direct relocation and rejects unavailable capacity',()=>{const {g,stand}=fixture();let row=deliverability(g).sites.find(s=>s.id===stand.id)!;expect(row.crews.length).toBeGreaterThan(0);expect(row.crews[0].workHours).toBe(g.region.crews[0].hours);for(const c of g.region.crews)c.hours=0;for(const t of g.region.trucks)t.hours=0;row=deliverability(g).sites.find(s=>s.id===stand.id)!;expect(row.crews).toEqual([]);expect(row.connections).toEqual([]);});
 it('does not let a hidden receiving disruption leak into screening',()=>{const {g,stand}=fixture();g.region.disruptions=[];const before=deliverability(g).sites.find(s=>s.id===stand.id)!.connections;expect(before.length).toBeGreaterThan(0);const target=before[0].mill;g.region.disruptions=[{id:'hidden',title:'Hidden',description:'Test',kind:'mill',target,week:1,endWeek:2,revealWeek:2,repairCost:100,repairWeeks:1}];expect(deliverability(g).sites.find(s=>s.id===stand.id)!.connections).toEqual(before);g.region.disruptions![0].revealWeek=1;expect(deliverability(g).sites.find(s=>s.id===stand.id)!.connections.every(c=>c.mill!==target)).toBe(true);});
 it('does not confuse closed harvest terrain with road access to already-cut stock',()=>{const {g,stand}=fixture();stand.terrain=4;g.region.weather[g.weatherId].forecast[stand.zone][0]='thaw';const row=deliverability(g).sites.find(s=>s.id===stand.id)!;expect(row.crews).toEqual([]);expect(row.connections.length).toBeGreaterThan(0);});
 it('does not use surplus at one mill to hide another mill commitment gap',()=>{const {g}=fixture(),p=g.region.products[0].id,[a,b]=g.region.mills;g.plan.targets=Object.fromEntries(g.region.mills.map(m=>[m.id,{}]));g.plan.targets[a.id]={[p]:100};g.plan.targets[b.id]={[p]:100};const report=advance(createGame(quebec)).history[0];report.delivered={[p]:200};report.millDeliveries={[a.id]:{[p]:200}};vi.spyOn(planning,'forecastOutcome').mockReturnValue({report,problems:[]});expect(deliverability(g).products.find(row=>row.product.id===p)!.remainingAfterForecast).toBe(100);});
 it('leaves ambiguous mixed-channel commitment estimates unresolved',()=>{const {g,stand}=fixture();g.plan.trucks[g.region.trucks[0].id]=[{stand:stand.id,mill:g.region.mills[0].id,product:g.region.products[0].id,loads:1,spot:true}];expect(deliverability(g).products.every(p=>p.remainingAfterForecast===null)).toBe(true);});
});
