export const eightCompanies=Array.from({length:8},(_,i)=>String(i+1));
export type EightRule='equal'|'standalone';
export interface EightRound {version:1;round:number;rule:EightRule;accepted:string[];revealed:boolean;reflection:string}
export const newEightRound=(round=1):EightRound=>({version:1,round,rule:'equal',accepted:[],revealed:false,reflection:''});
export function standaloneEight(id:string){return 120+Number(id)*15;}
function value(members:string[],round:number){if(members.length<2)return 0;let pairs=0;for(let i=0;i<members.length;i++)for(let j=i+1;j<members.length;j++){const a=Number(members[i]),b=Number(members[j]);pairs+=4+((a*13+b*7+round*3)%17)+(a===8||b===8?0:8);}return pairs-8*Math.max(0,members.length-2)**2;}
function shares(members:string[],state:EightRound){const total=value(members,state.round),base=members.reduce((n,id)=>n+standaloneEight(id),0);return Object.fromEntries(members.map(id=>[id,total*(state.rule==='equal'?1/members.length:standaloneEight(id)/base)]));}
export function chooseEightRule(state:EightRound,rule:EightRule){if(state.revealed)throw Error('The sharing rule is frozen for this round.');if(!['equal','standalone'].includes(rule))throw Error('Unknown sharing rule.');return {...state,rule,accepted:[]};}
export function acceptEight(state:EightRound,id:string,accepted:boolean){if(state.revealed||!eightCompanies.includes(id))throw Error('This agreement cannot be changed.');return {...state,accepted:eightCompanies.filter(c=>c===id?accepted:state.accepted.includes(c))};}
export function revealEight(state:EightRound){if(state.accepted.length!==8||!eightCompanies.every(id=>state.accepted.includes(id)))throw Error('All eight companies must accept the sharing rule first.');return {...state,revealed:true};}
export function eightDisclosure(state:EightRound){
 const pairs=eightCompanies.flatMap((a,i)=>eightCompanies.slice(i+1).map(b=>({members:[a,b],savings:value([a,b],state.round)})));
 if(!state.revealed)return {pairs,large:null};
 const allocation=shares(eightCompanies,state),grand=value(eightCompanies,state.round);
 const exclusions=eightCompanies.map(excluded=>{const members=eightCompanies.filter(id=>id!==excluded),allocated=shares(members,state);return {excluded,savings:value(members,state.round),delta:value(members,state.round)-grand,gainingMembers:members.filter(id=>allocated[id]>allocation[id]+1e-8),allocation:allocated};});
 const blocking=[];for(let mask=1;mask<255;mask++){const members=eightCompanies.filter((_,i)=>mask&(1<<i)),available=value(members,state.round),assigned=members.reduce((n,id)=>n+allocation[id],0);if(available>assigned+1e-8)blocking.push({members,gap:available-assigned});}
 blocking.sort((a,b)=>b.gap-a.gap);
 return {pairs,large:{grand,allocation,exclusions,blocking}};
}
export function parseEight(raw:string):EightRound {const p=JSON.parse(raw);if(!p||p.version!==1||!Number.isInteger(p.round)||p.round<1||p.round>1000000||!['equal','standalone'].includes(p.rule)||!Array.isArray(p.accepted)||p.accepted.some((id:unknown)=>typeof id!=='string'||!eightCompanies.includes(id))||new Set(p.accepted).size!==p.accepted.length||typeof p.revealed!=='boolean'||(p.revealed&&p.accepted.length!==8)||typeof p.reflection!=='string'||p.reflection.length>6000)throw Error('Invalid eight-company round.');return {version:1,round:p.round,rule:p.rule,accepted:p.accepted,reflection:p.reflection,revealed:p.revealed};}
export function eightPacket(state:EightRound){const d=eightDisclosure(state);return [`# Eight-company classroom exercise · round ${state.round}`,'Generated teaching coefficients in abstract cost units; not the original game data, campaign currency or an operational cost model. Local pass-and-play confirmations are not authenticated company signatures.',`Sharing rule: ${state.rule}. Accepted by: ${state.accepted.join(', ')||'none'}. Larger coalitions ${state.revealed?'revealed; rule frozen':'not revealed'}.`,'## Pair savings',...d.pairs.map(p=>`${p.members.join(' + ')}: ${p.savings}`),...(d.large?['## Revealed allocation',`Grand coalition savings: ${d.large.grand}`,...Object.entries(d.large.allocation).map(([id,n])=>`Company ${id}: ${n.toFixed(2)} savings`),'## Exclusion bargaining',...d.large.exclusions.map(e=>`Exclude ${e.excluded}: savings ${e.savings}; change from grand coalition ${e.delta}; incumbents receiving more under frozen rule: ${e.gainingMembers.join(', ')||'none'}.`),`Proper blocking coalitions: ${d.large.blocking.length}.`]:[]),'## Reflection',state.reflection||'No reflection recorded.','Why accept this rule before knowing larger coalitions? Who benefits from excluding a company? Does a blocking coalition’s total gain imply that every member benefits under the frozen rule? What would you change in a fresh round?'].join('\n\n');}
export function eightPrintPacket(state:EightRound){const text=eightPacket(state).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');return `<!doctype html><html lang="en"><meta charset="utf-8"><title>Eight-company reflection packet</title><style>body{max-width:850px;margin:32px auto;padding:0 20px;color:#172b21}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:15px/1.6 system-ui} @media print{body{margin:0;max-width:none}pre{font-size:11pt}}</style><body><pre>${text}</pre></body></html>`;}
