import {describe,it,expect} from 'vitest';
import {eightCompanies,newEightRound,eightDisclosure,eightPacket,eightPrintPacket,acceptEight,revealEight,chooseEightRule,parseEight} from './eight-company';
function agreed(){return eightCompanies.reduce((s,id)=>acceptEight(s,id,true),newEightRound());}
describe('eight-company staged local negotiation',()=>{
 it('discloses exactly the pairs before acceptance and no larger results in exports',()=>{const state=newEightRound();expect(eightDisclosure(state).pairs).toHaveLength(28);expect(eightDisclosure(state).large).toBeNull();expect(eightPacket(state)).not.toContain('Grand coalition savings:');expect(eightPrintPacket(state)).not.toContain('Grand coalition savings:');expect(()=>revealEight(state)).toThrow();});
 it('requires eight distinct acceptances, resets votes on rule change and freezes revealed rule',()=>{let s=agreed();s=chooseEightRule(s,'standalone');expect(s.accepted).toEqual([]);expect(()=>revealEight(s)).toThrow();s=eightCompanies.reduce((state,id)=>acceptEight(state,id,true),s);s=revealEight(s);expect(()=>chooseEightRule(s,'equal')).toThrow();expect(()=>acceptEight(s,'1',false)).toThrow();});
 it('conserves revealed coalition savings and evaluates all eight exclusion alternatives',()=>{const state=revealEight(agreed()),data=eightDisclosure(state).large!;expect(Object.values(data.allocation).reduce((n,v)=>n+v,0)).toBeCloseTo(data.grand,8);expect(data.exclusions).toHaveLength(8);for(const exclusion of data.exclusions){expect(Object.keys(exclusion.allocation)).toHaveLength(7);expect(exclusion.allocation[exclusion.excluded]).toBeUndefined();expect(Object.values(exclusion.allocation).reduce((n,v)=>n+v,0)).toBeCloseTo(exclusion.savings,8);}});
 it('restores disclosure gate and rejects forged inconsistent saves',()=>{const state=revealEight(agreed());expect(parseEight(JSON.stringify(state))).toEqual(state);expect(()=>parseEight(JSON.stringify({...state,accepted:['1']}))).toThrow();expect(()=>parseEight(JSON.stringify({...state,accepted:Array(8).fill('1')}))).toThrow();});
 it('escapes reflection text in printable HTML and starts a fresh disclosure stage',()=>{const state={...revealEight(agreed()),reflection:'<script>alert(1)</script>'};expect(eightPrintPacket(state)).toContain('&lt;script&gt;');expect(eightPrintPacket(state)).not.toContain('<script>');expect(eightDisclosure(newEightRound(2)).large).toBeNull();expect(eightDisclosure(newEightRound(2)).pairs).not.toEqual(eightDisclosure(newEightRound(1)).pairs);});
});
