import {describe,it,expect} from 'vitest';
import {createGame,advance,sum,draftPlan} from './engine';
import {mobilize,mobilizationQuote} from './mobilization';
import {recoveredMix,validateBucking} from './bucking';
import {parseGame,validateRegion} from './validation';
import {serializeGame} from './save-format';
import {quebec} from '../scenarios/quebec';
import {princeGeorge} from '../scenarios/prince-george';
import {forecastOutcome} from './planning';
describe('regional harvest choices',()=>{
 it('conserves bucked timber with forecast and persisted recovery',()=>{const g=createGame(quebec),c=g.region.crews[0],s=g.region.stands[0];g.crewPositions[c.id]=s.node;g.plan.crews[c.id]=[{stand:s.id,hours:8,bucking:'pulp-priority'}];const mix=recoveredMix(g.region,s.mix,'pulp-priority');expect(sum(mix)).toBeCloseTo(sum(s.mix));expect(mix['soft-saw']).toBeCloseTo(s.mix['soft-saw']*.6);for(const z of g.region.zones)g.region.weather[g.weatherId].actual[z.id]=[...g.region.weather[g.weatherId].forecast[z.id]];const copy=parseGame(serializeGame(g)),preview=forecastOutcome(copy).report!,next=advance(copy),h=next.history[0];expect(h.harvested).toEqual(preview.harvested);expect(sum(h.harvested)).toBeCloseTo(g.stands[0].remaining-next.stands[0].remaining);expect(h.harvested['soft-pulp']/sum(h.harvested)).toBeCloseTo(mix['soft-pulp']);expect(h.production?.[0].bucking).toBe('pulp-priority');expect(parseGame(serializeGame(next)).history[0].production?.[0].bucking).toBe('pulp-priority');});
 it('rejects creation of volume, quality upgrades and unknown profiles',()=>{const r=structuredClone(quebec);r.buckingProfiles!.bad={name:'Bad',cost:1,productivity:1,recovery:{'soft-pulp':{'soft-saw':1}}};expect(()=>validateBucking(r)).toThrow(/quality/);r.buckingProfiles!.bad.recovery={'soft-pulp':{'soft-pulp':1.1}};expect(()=>validateRegion(r)).toThrow();const g=createGame(quebec);g.plan.crews.C1=[{stand:'Q01',hours:8,bucking:'missing'}];expect(()=>advance(g)).toThrow(/production order/);});
 it('charges repeated mobilization and locks after first operations, surviving saves',()=>{const g=createGame(quebec),c=g.region.crews[0],to=g.region.mobilization!.allowedNodes.find(n=>n!==c.node)!;const quote=mobilizationQuote(g,'crew',c.id,to),m=mobilize(g,'crew',c.id,to);expect(m.cash).toBeCloseTo(g.cash-quote.cost);expect(m.crewPositions[c.id]).toBe(to);expect(g.crewPositions[c.id]).toBe(c.node);expect(()=>mobilize(m,'crew',c.id,to)).toThrow(/already/);const back=mobilize(m,'crew',c.id,c.node);expect(back.cash).toBeLessThan(m.cash);const restored=parseGame(serializeGame(back));const next=advance(restored);expect(next.mobilization?.locked).toBe(true);expect(next.history[0].ledger.filter(e=>e.category==='mobilization')).toHaveLength(2);expect(()=>mobilize(next,'crew',c.id,to)).toThrow(/closed/);});
 it('uses BC staging nodes and respects money and time allowances',()=>{const g=createGame(princeGeorge);validateRegion(g.region);expect(g.region.mobilization!.allowedNodes.every(id=>g.region.roads.nodes.some(n=>n.id===id))).toBe(true);const q=createGame(quebec);q.region.mobilization!.maxHoursPerResource=.00001;expect(()=>mobilize(q,'crew','C1','t1')).toThrow(/allowance/);q.region.mobilization!.maxHoursPerResource=16;q.cash=0;expect(()=>mobilize(q,'crew','C1','t1')).toThrow(/cash/);});
 it('drafts a profile-aware dispatch and rejects an unknown draft option',()=>{const g=createGame(quebec),draft=draftPlan(g,{bucking:'pulp-priority'});expect(Object.values(draft.plan.crews).flat().every(o=>o.bucking==='pulp-priority')).toBe(true);expect(()=>draftPlan(g,{bucking:'invalid'})).toThrow();});
});
