import {reciprocalServiceProgress} from './reciprocal';
import type {Game} from './types';
export function reciprocalDebrief(game:Game,language:'en'|'fr'):string[]{
 const fr=language==='fr',number=(n:number)=>(Math.abs(n)<.005?0:n).toLocaleString(fr?'fr-CA':'en-CA',{minimumFractionDigits:2,maximumFractionDigits:2});
 const terms=new Map((game.region.reciprocalPairs??[]).map(pair=>[pair.id,pair]));
 for(const [id,agreement] of Object.entries(game.reciprocal??{}))terms.set(id,agreement.terms);
 const rows=[...terms].map(([id,pair])=>({id,pair,saved:game.reciprocal?.[id]}));
 const cell=(value:string)=>value.replace(/\\/g,'\\\\').replace(/\|/g,'\\|').replace(/[\r\n]+/g,' ');
 const lines=[fr?'## Livraisons réciproques':'## Reciprocal deliveries',fr?'Volumes par côté. Les économies peuvent être négatives. Les transferts entre entreprises répartissent les économies; ils ne créent pas de trésorerie supplémentaire pour le réseau.':'Volumes are per side. Savings can be negative. Company transfers allocate savings; they do not create additional network cash.'];
 if(!rows.length)return [...lines,fr?'Aucun accord réciproque enregistré.':'No reciprocal agreement recorded.'];
 lines.push(fr?'| Accord | Renouvelle | Tours | m³ par côté | Économies conjointes | Part A | Part B | Transfert vers A |':'| Agreement | Renews | Turns | m³ per side | Joint savings | A share | B share | Transfer to A |','|---|---|---|---:|---:|---:|---:|---:|');
 for(const {id,pair,saved:a}of rows)lines.push(`| ${cell(id)} | ${cell(pair.renews??'—')} | ${pair.opens}–${pair.deadline} | ${number(a?.movedM3??0)} | ${number(a?.savings??0)} | ${number(a?.shareA??0)} | ${number(a?.shareB??0)} | ${number(a?.transferToA??0)} |`);
 lines.push(fr?'### Économies avant et après transfert':'### Savings before and after transfer',fr?'| Accord | Entreprise | Avant transfert | Transfert reçu | Après transfert |':'| Agreement | Company | Before transfer | Transfer received | After transfer |','|---|---|---:|---:|---:|');
 for(const {id,saved:a} of rows){if(!a||a.movedM3<=0)continue;for(const company of ['A','B'] as const){const share=company==='A'?a.shareA:a.shareB,transfer=company==='A'?a.transferToA:-a.transferToA;lines.push(`| ${cell(id)} | ${company} | ${number(share-transfer)} | ${number(transfer)} | ${number(share)} |`);}}
 lines.push(fr?'Avant transfert : différence entre les coûts des trajets croisés réels et ceux des livraisons directes depuis les mêmes positions initiales. Les pertes sont négatives. Cette comparaison ne prouve pas la faisabilité du calendrier direct.':'Before transfer: the cost difference between actual cross-hauls and direct deliveries from the same opening positions. Losses are negative. This comparison does not prove the direct schedule was feasible.');
 lines.push(fr?'### Conditions et consentement':'### Terms and consent',fr?'| Accord | Trajets autorisés | Produit | Limite par côté (m³) | Réserve par site (m³) | Répartition figée | Accepté par |':'| Agreement | Permitted delivery routes | Product | Limit per side (m³) | Reserve per stand (m³) | Frozen sharing | Accepted by |','|---|---|---|---:|---:|---|---|');
 for(const {id,pair,saved:a}of rows){
  const method=pair.settlement==='no-cash'?(fr?'Sans compensation : économies propres':'No cash: own transport savings'):!a?(fr?'Pas encore choisie':'Not chosen yet'):a.method==='equal'?(fr?'Égale':'Equal'):(fr?'Proportionnelle au coût du transport direct':'Proportional to direct transport cost');
  lines.push(`| ${cell(id)} | ${cell(pair.standA)} → ${cell(pair.routing==='fixed'?pair.millA:pair.millB)}; ${cell(pair.standB)} → ${cell(pair.routing==='fixed'?pair.millB:pair.millA)} | ${cell(pair.product)} | ${number(pair.limitM3)} | ${number(pair.ownReserveM3)} | ${method} | ${a?.accepted.length?a.accepted.join(', '):(fr?'Aucune entreprise':'No company')} |`);
 }
 lines.push(fr?'Les deux entreprises doivent accepter les conditions avant toute livraison. Un renouvellement nécessite un nouveau consentement.':'Both companies must accept the terms before delivery. A renewal requires fresh consent.');
 lines.push(fr?'Perturbations : une paire bloquée ne livre aucun des deux chargements. Le stock non expédié vieillit normalement. Les fermetures ne prolongent pas l’échéance et ne suppriment pas les obligations envers les usines propres.':'Disruptions: a blocked load pair sends neither load. Unshipped stock ages normally. Closures do not extend the deadline or waive own-mill requirements.');
 lines.push(fr?'### Service des usines propres':'### Own-mill service',fr?'Les volumes ci-dessous comptent uniquement les livraisons ordinaires du site propre vers son usine, après le consentement des deux entreprises et avant la date limite. Aucun paiement de pénalité automatique.':'These volumes count only ordinary deliveries from each own supply to its own mill, after bilateral consent and through the deadline. No automatic cash penalty.',fr?'| Accord | Routage | Échéance | A livré / requis (m³) | B livré / requis (m³) | État |':'| Agreement | Routing | Deadline | A delivered / required (m³) | B delivered / required (m³) | Status |','|---|---|---:|---:|---:|---|');
 for(const {id,pair} of rows){const progress=reciprocalServiceProgress(game,id),labels={unaccepted:fr?'Clôturé sans accord':'Closed without agreement',pending:fr?'En attente':'Pending',active:fr?'En cours':'Active',fulfilled:fr?'Satisfait':'Fulfilled',shortfall:fr?'Déficit':'Shortfall',unknown:fr?'Non vérifiable':'Unknown'};lines.push(`| ${cell(id)} | ${pair.routing==='fixed'?(fr?'Fixe':'Fixed'):(fr?'Flexible':'Flexible')} | ${pair.deadline} | ${progress.status==='unknown'?'—':number(progress.A.delivered)} / ${number(progress.A.required)} | ${progress.status==='unknown'?'—':number(progress.B.delivered)} / ${number(progress.B.required)} | ${labels[progress.status]} |`);}
 lines.push(`${fr?'Devise':'Currency'}: ${game.region.currency}.`,fr?'Un transfert négatif vers A est dû à B. Les accords sans livraison restent à zéro.':'A negative transfer to A is owed to B. Agreements without deliveries remain at zero.');
 return lines;
}
