import {describe,it,expect} from 'vitest';
import {defaultObligations as d,transportObligations} from './transport-obligations';
describe('declared transportation shadow allocation',()=>{
 it('finds beneficial exchange blocked without compensation and certifies balanced transfers',()=>{const r=transportObligations(d);expect(r.flows).toEqual({aa:20,ab:80,ba:80,bb:20});expect(r.savings).toBe(1040);expect(r.comparisons[2].cross).toBe(0);expect(r.transferToA+r.transferToB).toBeCloseTo(0,6);expect(r.dual.objective).toBeCloseTo(r.total,6);expect(r.allocationA).toBeLessThanOrEqual(r.baselineA+1e-6);expect(r.allocationB).toBeLessThanOrEqual(r.baselineB+1e-6);});
 it('preserves both company supplies and mill demands for unequal volumes',()=>{const r=transportObligations({...d,volumeB:60});expect(r.flows.aa+r.flows.ab).toBe(100);expect(r.flows.ba+r.flows.bb).toBe(60);expect(r.flows.aa+r.flows.ba).toBe(100);expect(r.flows.ab+r.flows.bb).toBe(60);expect(r.flows.bb).toBeGreaterThanOrEqual(20);});
 it('keeps fixed obligations and unprofitable cross routes at baseline',()=>{const fixed=transportObligations({...d,ownMinimumA:100,ownMinimumB:100});expect(fixed.total).toBe(fixed.baseline);const bad=transportObligations({...d,costAB:100,costBA:100});expect(bad.flows.ab).toBe(0);expect(bad.total).toBe(bad.baseline);});
 it('permits no-cash exchange when both direct bills fall',()=>{const r=transportObligations({...d,costAB:5});expect(r.comparisons[2].cross).toBe(r.flows.ab);expect(r.comparisons[2].costA).toBeLessThan(r.baselineA);expect(r.comparisons[2].costB).toBeLessThan(r.baselineB);});
 it('checks strong duality and complementarity across varied bounded cases',()=>{for(let i=0;i<30;i++){const r=transportObligations({...d,volumeA:30+i,volumeB:40+i,ownMinimumA:i%10,ownMinimumB:i%7,costAA:i%11,costAB:(i*3)%17,costBA:(i*7)%19,costBB:(i*5)%13});expect(r.dual.gap).toBeCloseTo(0,5);for(const id of ['aa','ab','ba','bb'] as const){expect(r.dual.slacks[id]).toBeGreaterThanOrEqual(-1e-6);expect(r.flows[id]*r.dual.slacks[id]).toBeCloseTo(0,5);}expect(r.dual.mA*(r.flows.aa-r.settings.ownMinimumA)).toBeCloseTo(0,5);expect(r.dual.mB*(r.flows.bb-r.settings.ownMinimumB)).toBeCloseTo(0,5);}});
 it('handles degenerate equal-rate and zero-cost optima without inventing individual gains',()=>{for(const rate of [0,11]){const r=transportObligations({...d,costAA:rate,costAB:rate,costBA:rate,costBB:rate});expect(r.total).toBeCloseTo(r.baseline,6);expect(r.allocationA).toBeCloseTo(r.baselineA,6);expect(r.allocationB).toBeCloseTo(r.baselineB,6);expect(r.transferToA+r.transferToB).toBeCloseTo(0,6);expect(r.dual.gap).toBeCloseTo(0,6);}});
 it('rejects obligations exceeding supply',()=>{expect(()=>transportObligations({...d,ownMinimumA:101})).toThrow();});
});
